security:
    encoders:
        App\Entity\User:
            algorithm: auto
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: false
            lazy: true
            provider: app_user_provider
            guard:
                authenticators: [App\Security\LoginAuthenticator]
            logout:
                path: app_logout
    access_control:
        -
            path: ^/home
            roles:
                - ROLE_USER
                - ROLE_5918
                - ROLE_ADMIN
        -
            path: ^/cliente
            roles:
                - ROLE_USER
                - ROLE_ADMIN
                - ROLE_5918
        -
            path: ^/registrar
            roles:
                - ROLE_USER
                - ROLE_ADMIN
        -
            path: ^/edit
            roles:
                - ROLE_USER
                - ROLE_ADMIN
                - ROLE_5918
        -
            path: ^/api
            roles:
                - ROLE_USER
                - ROLE_ADMIN
        -
            path: ^/select
            roles:
                - ROLE_USER
                - ROLE_ADMIN
        -
            path: ^/confirm
            roles:
                - ROLE_USER
                - ROLE_ADMIN
        -
            path: ^/contabilidad
            roles:
                - ROLE_ADMIN
                - ROLE_USER
        -
            path: ^/contabilidad/config
            roles:
                - ROLE_ADMIN
                - ROLE_USER
        -
            path: ^/config
            roles:
                - ROLE_ADMIN
                - ROLE_USER
        -
            path: ^/turismo
            roles:
                - ROLE_USER
                - ROLE_5918
                - ROLE_ADMIN
        -
            path: ^/paymentreport.factura
            roles:
                - ROLE_USER
                - ROLE_ADMIN
        -
            path: ^/paymentreport
            roles:
                - ROLE_USER
                - ROLE_ADMIN
        -
            path: ^/efectivo
            roles:
                - ROLE_USER
                - ROLE_ADMIN
        -
            path: ^/permisos-por-rol
            roles:
                - ROLE_USER
                - ROLE_ADMIN
        -
            path: ^/cliente-index
            roles:
                - ROLE_USER
                - ROLE_5918
                - ROLE_ADMIN
        -
            path: ^/cliente-edit
            roles:
                - ROLE_USER
                - ROLE_5918
                - ROLE_ADMIN
        -
            path: ^/registrar-cliente
            roles:
                - ROLE_USER
                - ROLE_5918
                - ROLE_ADMIN
        -
            path: ^/edit-save
            roles:
                - ROLE_USER
                - ROLE_5918
                - ROLE_ADMIN
       
