<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20201216141446 extends AbstractMigration
{
    public function getDescription() : string
    {
        return '';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE almacen_ocupado ADD CONSTRAINT FK_AA53605839161EBF FOREIGN KEY (id_almacen_id) REFERENCES almacen (id)');
        $this->addSql('ALTER TABLE almacen_ocupado ADD CONSTRAINT FK_AA5360587EB2C349 FOREIGN KEY (id_usuario_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE area_responsabilidad ADD CONSTRAINT FK_F469C2BA1D34FA6B FOREIGN KEY (id_unidad_id) REFERENCES unidad (id)');
        $this->addSql('ALTER TABLE asiento ADD id_tipo_comprobante_id INT DEFAULT NULL, ADD id_comprobante_id INT DEFAULT NULL, ADD id_factura_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE asiento ADD CONSTRAINT FK_71D6D35C1ADA4D3F FOREIGN KEY (id_cuenta_id) REFERENCES cuenta (id)');
        $this->addSql('ALTER TABLE asiento ADD CONSTRAINT FK_71D6D35C2D412F53 FOREIGN KEY (id_subcuenta_id) REFERENCES subcuenta (id)');
        $this->addSql('ALTER TABLE asiento ADD CONSTRAINT FK_71D6D35C6601BA07 FOREIGN KEY (id_documento_id) REFERENCES documento (id)');
        $this->addSql('ALTER TABLE asiento ADD CONSTRAINT FK_71D6D35C39161EBF FOREIGN KEY (id_almacen_id) REFERENCES almacen (id)');
        $this->addSql('ALTER TABLE asiento ADD CONSTRAINT FK_71D6D35CC59B01FF FOREIGN KEY (id_centro_costo_id) REFERENCES centro_costo (id)');
        $this->addSql('ALTER TABLE asiento ADD CONSTRAINT FK_71D6D35CF66372E9 FOREIGN KEY (id_elemento_gasto_id) REFERENCES elemento_gasto (id)');
        $this->addSql('ALTER TABLE asiento ADD CONSTRAINT FK_71D6D35C71381BB3 FOREIGN KEY (id_orden_trabajo_id) REFERENCES orden_trabajo (id)');
        $this->addSql('ALTER TABLE asiento ADD CONSTRAINT FK_71D6D35CF5DBAF2B FOREIGN KEY (id_expediente_id) REFERENCES expediente (id)');
        $this->addSql('ALTER TABLE asiento ADD CONSTRAINT FK_71D6D35CE8F12801 FOREIGN KEY (id_proveedor_id) REFERENCES proveedor (id)');
        $this->addSql('ALTER TABLE asiento ADD CONSTRAINT FK_71D6D35C1D34FA6B FOREIGN KEY (id_unidad_id) REFERENCES unidad (id)');
        $this->addSql('ALTER TABLE asiento ADD CONSTRAINT FK_71D6D35CEF5F7851 FOREIGN KEY (id_tipo_comprobante_id) REFERENCES tipo_comprobante (id)');
        $this->addSql('ALTER TABLE asiento ADD CONSTRAINT FK_71D6D35C1800963C FOREIGN KEY (id_comprobante_id) REFERENCES registro_comprobantes (id)');
        $this->addSql('ALTER TABLE asiento ADD CONSTRAINT FK_71D6D35C55C5F988 FOREIGN KEY (id_factura_id) REFERENCES factura (id)');
        $this->addSql('CREATE INDEX IDX_71D6D35CEF5F7851 ON asiento (id_tipo_comprobante_id)');
        $this->addSql('CREATE INDEX IDX_71D6D35C1800963C ON asiento (id_comprobante_id)');
        $this->addSql('CREATE INDEX IDX_71D6D35C55C5F988 ON asiento (id_factura_id)');
        $this->addSql('ALTER TABLE centro_costo ADD CONSTRAINT FK_749608CE1D34FA6B FOREIGN KEY (id_unidad_id) REFERENCES unidad (id)');
        $this->addSql('ALTER TABLE cierre ADD CONSTRAINT FK_D0DCFCC739161EBF FOREIGN KEY (id_almacen_id) REFERENCES almacen (id)');
        $this->addSql('ALTER TABLE cierre ADD CONSTRAINT FK_D0DCFCC77EB2C349 FOREIGN KEY (id_usuario_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE cierre_diario ADD CONSTRAINT FK_F3D0CD8939161EBF FOREIGN KEY (id_almacen_id) REFERENCES almacen (id)');
        $this->addSql('ALTER TABLE cierre_diario ADD CONSTRAINT FK_F3D0CD897EB2C349 FOREIGN KEY (id_usuario_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE cobros_pagos ADD CONSTRAINT FK_D9581D1655C5F988 FOREIGN KEY (id_factura_id) REFERENCES factura (id)');
        $this->addSql('ALTER TABLE cobros_pagos ADD CONSTRAINT FK_D9581D1626990C38 FOREIGN KEY (id_informe_id) REFERENCES informe_recepcion (id)');
        $this->addSql('ALTER TABLE cobros_pagos ADD CONSTRAINT FK_D9581D16E8F12801 FOREIGN KEY (id_proveedor_id) REFERENCES proveedor (id)');
        $this->addSql('ALTER TABLE comprobante_cierre ADD CONSTRAINT FK_D03EA4C51800963C FOREIGN KEY (id_comprobante_id) REFERENCES registro_comprobantes (id)');
        $this->addSql('ALTER TABLE comprobante_cierre ADD CONSTRAINT FK_D03EA4C545F8C94C FOREIGN KEY (id_cierre_id) REFERENCES cierre (id)');
        $this->addSql('ALTER TABLE configuracion_inicial ADD CONSTRAINT FK_8521BE24404AE9D2 FOREIGN KEY (id_modulo_id) REFERENCES modulo (id)');
        $this->addSql('ALTER TABLE configuracion_inicial ADD CONSTRAINT FK_8521BE247A4F962 FOREIGN KEY (id_tipo_documento_id) REFERENCES tipo_documento (id)');
        $this->addSql('ALTER TABLE contratos_cliente ADD CONSTRAINT FK_29A5BB477BF9CE86 FOREIGN KEY (id_cliente_id) REFERENCES cliente_contabilidad (id)');
        $this->addSql('ALTER TABLE contratos_cliente ADD CONSTRAINT FK_29A5BB47374388F5 FOREIGN KEY (id_moneda_id) REFERENCES moneda (id)');
        $this->addSql('ALTER TABLE cuadre_diario ADD CONSTRAINT FK_60ABEFD91ADA4D3F FOREIGN KEY (id_cuenta_id) REFERENCES cuenta (id)');
        $this->addSql('ALTER TABLE cuadre_diario ADD CONSTRAINT FK_60ABEFD92D412F53 FOREIGN KEY (id_subcuenta_id) REFERENCES subcuenta (id)');
        $this->addSql('ALTER TABLE cuadre_diario ADD CONSTRAINT FK_60ABEFD945F8C94C FOREIGN KEY (id_cierre_id) REFERENCES cierre (id)');
        $this->addSql('ALTER TABLE cuadre_diario ADD CONSTRAINT FK_60ABEFD939161EBF FOREIGN KEY (id_almacen_id) REFERENCES almacen (id)');
        $this->addSql('ALTER TABLE cuenta ADD CONSTRAINT FK_31C7BFCF45E7F350 FOREIGN KEY (id_tipo_cuenta_id) REFERENCES tipo_cuenta (id)');
        $this->addSql('ALTER TABLE cuenta_criterio_analisis ADD CONSTRAINT FK_AF040B091ADA4D3F FOREIGN KEY (id_cuenta_id) REFERENCES cuenta (id)');
        $this->addSql('ALTER TABLE cuenta_criterio_analisis ADD CONSTRAINT FK_AF040B095ABBE5F6 FOREIGN KEY (id_criterio_analisis_id) REFERENCES criterio_analisis (id)');
        $this->addSql('ALTER TABLE cuentas_cliente ADD CONSTRAINT FK_64653310374388F5 FOREIGN KEY (id_moneda_id) REFERENCES moneda (id)');
        $this->addSql('ALTER TABLE cuentas_cliente ADD CONSTRAINT FK_646533107BF9CE86 FOREIGN KEY (id_cliente_id) REFERENCES cliente_contabilidad (id)');
        $this->addSql('ALTER TABLE custom_user ADD CONSTRAINT FK_8CE51EB479F37AE5 FOREIGN KEY (id_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE depreciacion ADD CONSTRAINT FK_D618AE145832E72E FOREIGN KEY (id_activo_fijo_id) REFERENCES activo_fijo (id)');
        $this->addSql('ALTER TABLE devolucion ADD CONSTRAINT FK_524D9F676601BA07 FOREIGN KEY (id_documento_id) REFERENCES documento (id)');
        $this->addSql('ALTER TABLE devolucion ADD CONSTRAINT FK_524D9F671D34FA6B FOREIGN KEY (id_unidad_id) REFERENCES unidad (id)');
        $this->addSql('ALTER TABLE devolucion ADD CONSTRAINT FK_524D9F6739161EBF FOREIGN KEY (id_almacen_id) REFERENCES almacen (id)');
        $this->addSql('ALTER TABLE devolucion ADD CONSTRAINT FK_524D9F67C59B01FF FOREIGN KEY (id_centro_costo_id) REFERENCES centro_costo (id)');
        $this->addSql('ALTER TABLE devolucion ADD CONSTRAINT FK_524D9F67F66372E9 FOREIGN KEY (id_elemento_gasto_id) REFERENCES elemento_gasto (id)');
        $this->addSql('ALTER TABLE devolucion ADD CONSTRAINT FK_524D9F675074DD86 FOREIGN KEY (id_orden_tabajo_id) REFERENCES orden_trabajo (id)');
        $this->addSql('ALTER TABLE documento ADD CONSTRAINT FK_B6B12EC739161EBF FOREIGN KEY (id_almacen_id) REFERENCES almacen (id)');
        $this->addSql('ALTER TABLE documento ADD CONSTRAINT FK_B6B12EC71D34FA6B FOREIGN KEY (id_unidad_id) REFERENCES unidad (id)');
        $this->addSql('ALTER TABLE documento ADD CONSTRAINT FK_B6B12EC7374388F5 FOREIGN KEY (id_moneda_id) REFERENCES moneda (id)');
        $this->addSql('ALTER TABLE documento ADD CONSTRAINT FK_B6B12EC77A4F962 FOREIGN KEY (id_tipo_documento_id) REFERENCES tipo_documento (id)');
        $this->addSql('ALTER TABLE documento ADD CONSTRAINT FK_B6B12EC74832F387 FOREIGN KEY (id_documento_cancelado_id) REFERENCES documento (id)');
        $this->addSql('ALTER TABLE empleado ADD CONSTRAINT FK_D9D9BF521D34FA6B FOREIGN KEY (id_unidad_id) REFERENCES unidad (id)');
        $this->addSql('ALTER TABLE empleado ADD CONSTRAINT FK_D9D9BF52D1E12F15 FOREIGN KEY (id_cargo_id) REFERENCES cargo (id)');
        $this->addSql('ALTER TABLE empleado ADD CONSTRAINT FK_D9D9BF527EB2C349 FOREIGN KEY (id_usuario_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE expediente ADD CONSTRAINT FK_D59CA4131D34FA6B FOREIGN KEY (id_unidad_id) REFERENCES unidad (id)');
        $this->addSql('ALTER TABLE factura ADD CONSTRAINT FK_F9EBA00968BCB606 FOREIGN KEY (id_contrato_id) REFERENCES contratos_cliente (id)');
        $this->addSql('ALTER TABLE factura ADD CONSTRAINT FK_F9EBA0091D34FA6B FOREIGN KEY (id_unidad_id) REFERENCES unidad (id)');
        $this->addSql('ALTER TABLE factura ADD CONSTRAINT FK_F9EBA0097EB2C349 FOREIGN KEY (id_usuario_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE factura ADD CONSTRAINT FK_F9EBA009C59B01FF FOREIGN KEY (id_centro_costo_id) REFERENCES centro_costo (id)');
        $this->addSql('ALTER TABLE factura ADD CONSTRAINT FK_F9EBA00971381BB3 FOREIGN KEY (id_orden_trabajo_id) REFERENCES orden_trabajo (id)');
        $this->addSql('ALTER TABLE factura ADD CONSTRAINT FK_F9EBA009F66372E9 FOREIGN KEY (id_elemento_gasto_id) REFERENCES elemento_gasto (id)');
        $this->addSql('ALTER TABLE factura ADD CONSTRAINT FK_F9EBA009F5DBAF2B FOREIGN KEY (id_expediente_id) REFERENCES expediente (id)');
        $this->addSql('ALTER TABLE factura ADD CONSTRAINT FK_F9EBA0094F4C4E26 FOREIGN KEY (id_categoria_cliente_id) REFERENCES categoria_cliente (id)');
        $this->addSql('ALTER TABLE factura ADD CONSTRAINT FK_F9EBA009C37A5552 FOREIGN KEY (id_termino_pago_id) REFERENCES termino_pago (id)');
        $this->addSql('ALTER TABLE factura ADD CONSTRAINT FK_F9EBA009374388F5 FOREIGN KEY (id_moneda_id) REFERENCES moneda (id)');
        $this->addSql('ALTER TABLE factura ADD CONSTRAINT FK_F9EBA00999274826 FOREIGN KEY (id_factura_cancela_id) REFERENCES factura (id)');
        $this->addSql('ALTER TABLE factura_documento ADD CONSTRAINT FK_CCC060C155C5F988 FOREIGN KEY (id_factura_id) REFERENCES factura (id)');
        $this->addSql('ALTER TABLE factura_documento ADD CONSTRAINT FK_CCC060C16601BA07 FOREIGN KEY (id_documento_id) REFERENCES documento (id)');
        $this->addSql('ALTER TABLE factura_documento ADD CONSTRAINT FK_CCC060C1EC34F77F FOREIGN KEY (id_movimiento_venta_id) REFERENCES movimiento_venta (id)');
        $this->addSql('ALTER TABLE facturas_comprobante ADD CONSTRAINT FK_6FD2F19B55C5F988 FOREIGN KEY (id_factura_id) REFERENCES factura (id)');
        $this->addSql('ALTER TABLE facturas_comprobante ADD CONSTRAINT FK_6FD2F19B1800963C FOREIGN KEY (id_comprobante_id) REFERENCES registro_comprobantes (id)');
        $this->addSql('ALTER TABLE facturas_comprobante ADD CONSTRAINT FK_6FD2F19B1D34FA6B FOREIGN KEY (id_unidad_id) REFERENCES unidad (id)');
        $this->addSql('ALTER TABLE informe_recepcion ADD CONSTRAINT FK_62A4EBD6601BA07 FOREIGN KEY (id_documento_id) REFERENCES documento (id)');
        $this->addSql('ALTER TABLE informe_recepcion ADD CONSTRAINT FK_62A4EBDE8F12801 FOREIGN KEY (id_proveedor_id) REFERENCES proveedor (id)');
        $this->addSql('ALTER TABLE mercancia ADD CONSTRAINT FK_9D094AE0E2C70A62 FOREIGN KEY (id_amlacen_id) REFERENCES almacen (id)');
        $this->addSql('ALTER TABLE mercancia ADD CONSTRAINT FK_9D094AE0E16A5625 FOREIGN KEY (id_unidad_medida_id) REFERENCES unidad_medida (id)');
        $this->addSql('ALTER TABLE mercancia_producto ADD CONSTRAINT FK_3F705CF59F287F54 FOREIGN KEY (id_mercancia_id) REFERENCES mercancia (id)');
        $this->addSql('ALTER TABLE mercancia_producto ADD CONSTRAINT FK_3F705CF56E57A479 FOREIGN KEY (id_producto_id) REFERENCES producto (id)');
        $this->addSql('ALTER TABLE movimiento ADD CONSTRAINT FK_C8FF107AD1CE493D FOREIGN KEY (id_tipo_documento_activo_fijo_id) REFERENCES tipo_documento_activo_fijo (id)');
        $this->addSql('ALTER TABLE movimiento ADD CONSTRAINT FK_C8FF107ADB763453 FOREIGN KEY (id_tipo_movimiento_id) REFERENCES tipo_movimiento (id)');
        $this->addSql('ALTER TABLE movimiento ADD CONSTRAINT FK_C8FF107A873C7FC7 FOREIGN KEY (id_unidad_origen_id) REFERENCES unidad (id)');
        $this->addSql('ALTER TABLE movimiento ADD CONSTRAINT FK_C8FF107A4F781EA FOREIGN KEY (id_unidad_destino_id) REFERENCES unidad (id)');
        $this->addSql('ALTER TABLE movimiento_activo_fijo ADD CONSTRAINT FK_A985A0DA1D34FA6B FOREIGN KEY (id_unidad_id) REFERENCES unidad (id)');
        $this->addSql('ALTER TABLE movimiento_activo_fijo ADD CONSTRAINT FK_A985A0DA5832E72E FOREIGN KEY (id_activo_fijo_id) REFERENCES activo_fijo (id)');
        $this->addSql('ALTER TABLE movimiento_activo_fijo ADD CONSTRAINT FK_A985A0DADB763453 FOREIGN KEY (id_tipo_movimiento_id) REFERENCES tipo_movimiento (id)');
        $this->addSql('ALTER TABLE movimiento_activo_fijo ADD CONSTRAINT FK_A985A0DA1ADA4D3F FOREIGN KEY (id_cuenta_id) REFERENCES cuenta (id)');
        $this->addSql('ALTER TABLE movimiento_activo_fijo ADD CONSTRAINT FK_A985A0DA2D412F53 FOREIGN KEY (id_subcuenta_id) REFERENCES subcuenta (id)');
        $this->addSql('ALTER TABLE movimiento_activo_fijo ADD CONSTRAINT FK_A985A0DA7EB2C349 FOREIGN KEY (id_usuario_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE movimiento_mercancia ADD CONSTRAINT FK_44876BD79F287F54 FOREIGN KEY (id_mercancia_id) REFERENCES mercancia (id)');
        $this->addSql('ALTER TABLE movimiento_mercancia ADD CONSTRAINT FK_44876BD76601BA07 FOREIGN KEY (id_documento_id) REFERENCES documento (id)');
        $this->addSql('ALTER TABLE movimiento_mercancia ADD CONSTRAINT FK_44876BD77A4F962 FOREIGN KEY (id_tipo_documento_id) REFERENCES tipo_documento (id)');
        $this->addSql('ALTER TABLE movimiento_mercancia ADD CONSTRAINT FK_44876BD77EB2C349 FOREIGN KEY (id_usuario_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE movimiento_mercancia ADD CONSTRAINT FK_44876BD7C59B01FF FOREIGN KEY (id_centro_costo_id) REFERENCES centro_costo (id)');
        $this->addSql('ALTER TABLE movimiento_mercancia ADD CONSTRAINT FK_44876BD7F66372E9 FOREIGN KEY (id_elemento_gasto_id) REFERENCES elemento_gasto (id)');
        $this->addSql('ALTER TABLE movimiento_mercancia ADD CONSTRAINT FK_44876BD739161EBF FOREIGN KEY (id_almacen_id) REFERENCES almacen (id)');
        $this->addSql('ALTER TABLE movimiento_mercancia ADD CONSTRAINT FK_44876BD7F5DBAF2B FOREIGN KEY (id_expediente_id) REFERENCES expediente (id)');
        $this->addSql('ALTER TABLE movimiento_mercancia ADD CONSTRAINT FK_44876BD771381BB3 FOREIGN KEY (id_orden_trabajo_id) REFERENCES orden_trabajo (id)');
        $this->addSql('ALTER TABLE movimiento_mercancia ADD CONSTRAINT FK_44876BD755C5F988 FOREIGN KEY (id_factura_id) REFERENCES factura (id)');
        $this->addSql('ALTER TABLE movimiento_mercancia ADD CONSTRAINT FK_44876BD7571159DE FOREIGN KEY (id_movimiento_cancelado_id) REFERENCES movimiento_mercancia (id)');
        $this->addSql('ALTER TABLE movimiento_producto ADD id_movimiento_cancelado_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE movimiento_producto ADD CONSTRAINT FK_FFC0EDFC6E57A479 FOREIGN KEY (id_producto_id) REFERENCES producto (id)');
        $this->addSql('ALTER TABLE movimiento_producto ADD CONSTRAINT FK_FFC0EDFC6601BA07 FOREIGN KEY (id_documento_id) REFERENCES documento (id)');
        $this->addSql('ALTER TABLE movimiento_producto ADD CONSTRAINT FK_FFC0EDFC7A4F962 FOREIGN KEY (id_tipo_documento_id) REFERENCES tipo_documento (id)');
        $this->addSql('ALTER TABLE movimiento_producto ADD CONSTRAINT FK_FFC0EDFC7EB2C349 FOREIGN KEY (id_usuario_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE movimiento_producto ADD CONSTRAINT FK_FFC0EDFCC59B01FF FOREIGN KEY (id_centro_costo_id) REFERENCES centro_costo (id)');
        $this->addSql('ALTER TABLE movimiento_producto ADD CONSTRAINT FK_FFC0EDFCF66372E9 FOREIGN KEY (id_elemento_gasto_id) REFERENCES elemento_gasto (id)');
        $this->addSql('ALTER TABLE movimiento_producto ADD CONSTRAINT FK_FFC0EDFC39161EBF FOREIGN KEY (id_almacen_id) REFERENCES almacen (id)');
        $this->addSql('ALTER TABLE movimiento_producto ADD CONSTRAINT FK_FFC0EDFC71381BB3 FOREIGN KEY (id_orden_trabajo_id) REFERENCES orden_trabajo (id)');
        $this->addSql('ALTER TABLE movimiento_producto ADD CONSTRAINT FK_FFC0EDFCF5DBAF2B FOREIGN KEY (id_expediente_id) REFERENCES expediente (id)');
        $this->addSql('ALTER TABLE movimiento_producto ADD CONSTRAINT FK_FFC0EDFC55C5F988 FOREIGN KEY (id_factura_id) REFERENCES factura (id)');
        $this->addSql('ALTER TABLE movimiento_producto ADD CONSTRAINT FK_FFC0EDFC571159DE FOREIGN KEY (id_movimiento_cancelado_id) REFERENCES movimiento_producto (id)');
        $this->addSql('CREATE INDEX IDX_FFC0EDFC571159DE ON movimiento_producto (id_movimiento_cancelado_id)');
        $this->addSql('ALTER TABLE movimiento_servicio ADD CONSTRAINT FK_93FD19C355C5F988 FOREIGN KEY (id_factura_id) REFERENCES factura (id)');
        $this->addSql('ALTER TABLE movimiento_servicio ADD CONSTRAINT FK_93FD19C371CAA3E7 FOREIGN KEY (servicio_id) REFERENCES servicios (id)');
        $this->addSql('ALTER TABLE movimiento_venta ADD CONSTRAINT FK_8E3F7AE555C5F988 FOREIGN KEY (id_factura_id) REFERENCES factura (id)');
        $this->addSql('ALTER TABLE movimiento_venta ADD CONSTRAINT FK_8E3F7AE539161EBF FOREIGN KEY (id_almacen_id) REFERENCES almacen (id)');
        $this->addSql('ALTER TABLE movimiento_venta ADD CONSTRAINT FK_8E3F7AE5D8F8B0AD FOREIGN KEY (id_centro_costo_acreedor_id) REFERENCES centro_costo (id)');
        $this->addSql('ALTER TABLE movimiento_venta ADD CONSTRAINT FK_8E3F7AE5FA3DF5CD FOREIGN KEY (id_orden_trabajo_acreedor_id) REFERENCES orden_trabajo (id)');
        $this->addSql('ALTER TABLE movimiento_venta ADD CONSTRAINT FK_8E3F7AE5F0821C98 FOREIGN KEY (id_elemento_gasto_acreedor_id) REFERENCES elemento_gasto (id)');
        $this->addSql('ALTER TABLE movimiento_venta ADD CONSTRAINT FK_8E3F7AE56EA527F2 FOREIGN KEY (id_expediente_acreedor_id) REFERENCES expediente (id)');
        $this->addSql('ALTER TABLE obligacion_cobro ADD CONSTRAINT FK_807C726D55C5F988 FOREIGN KEY (id_factura_id) REFERENCES factura (id)');
        $this->addSql('ALTER TABLE obligacion_pago ADD CONSTRAINT FK_403C9B3BE8F12801 FOREIGN KEY (id_proveedor_id) REFERENCES proveedor (id)');
        $this->addSql('ALTER TABLE obligacion_pago ADD CONSTRAINT FK_403C9B3B6601BA07 FOREIGN KEY (id_documento_id) REFERENCES documento (id)');
        $this->addSql('ALTER TABLE obligacion_pago ADD CONSTRAINT FK_403C9B3B1D34FA6B FOREIGN KEY (id_unidad_id) REFERENCES unidad (id)');
        $this->addSql('ALTER TABLE operaciones_comprobante_operaciones ADD CONSTRAINT FK_E7EA17E1ADA4D3F FOREIGN KEY (id_cuenta_id) REFERENCES cuenta (id)');
        $this->addSql('ALTER TABLE operaciones_comprobante_operaciones ADD CONSTRAINT FK_E7EA17E2D412F53 FOREIGN KEY (id_subcuenta_id) REFERENCES subcuenta (id)');
        $this->addSql('ALTER TABLE operaciones_comprobante_operaciones ADD CONSTRAINT FK_E7EA17EC59B01FF FOREIGN KEY (id_centro_costo_id) REFERENCES centro_costo (id)');
        $this->addSql('ALTER TABLE operaciones_comprobante_operaciones ADD CONSTRAINT FK_E7EA17E71381BB3 FOREIGN KEY (id_orden_trabajo_id) REFERENCES orden_trabajo (id)');
        $this->addSql('ALTER TABLE operaciones_comprobante_operaciones ADD CONSTRAINT FK_E7EA17EF66372E9 FOREIGN KEY (id_elemento_gasto_id) REFERENCES elemento_gasto (id)');
        $this->addSql('ALTER TABLE operaciones_comprobante_operaciones ADD CONSTRAINT FK_E7EA17EF5DBAF2B FOREIGN KEY (id_expediente_id) REFERENCES expediente (id)');
        $this->addSql('ALTER TABLE operaciones_comprobante_operaciones ADD CONSTRAINT FK_E7EA17EE8F12801 FOREIGN KEY (id_proveedor_id) REFERENCES proveedor (id)');
        $this->addSql('ALTER TABLE operaciones_comprobante_operaciones ADD CONSTRAINT FK_E7EA17EECB9FBA7 FOREIGN KEY (id_registro_comprobantes_id) REFERENCES registro_comprobantes (id)');
        $this->addSql('ALTER TABLE operaciones_comprobante_operaciones ADD CONSTRAINT FK_E7EA17E39161EBF FOREIGN KEY (id_almacen_id) REFERENCES almacen (id)');
        $this->addSql('ALTER TABLE operaciones_comprobante_operaciones ADD CONSTRAINT FK_E7EA17E1D34FA6B FOREIGN KEY (id_unidad_id) REFERENCES unidad (id)');
        $this->addSql('ALTER TABLE orden_trabajo ADD CONSTRAINT FK_4158A0241D34FA6B FOREIGN KEY (id_unidad_id) REFERENCES unidad (id)');
        $this->addSql('ALTER TABLE orden_trabajo ADD CONSTRAINT FK_4158A02439161EBF FOREIGN KEY (id_almacen_id) REFERENCES almacen (id)');
        $this->addSql('ALTER TABLE producto ADD CONSTRAINT FK_A7BB0615E2C70A62 FOREIGN KEY (id_amlacen_id) REFERENCES almacen (id)');
        $this->addSql('ALTER TABLE producto ADD CONSTRAINT FK_A7BB0615E16A5625 FOREIGN KEY (id_unidad_medida_id) REFERENCES unidad_medida (id)');
        $this->addSql('ALTER TABLE registro_comprobantes ADD CONSTRAINT FK_B2D1B2B21D34FA6B FOREIGN KEY (id_unidad_id) REFERENCES unidad (id)');
        $this->addSql('ALTER TABLE registro_comprobantes ADD CONSTRAINT FK_B2D1B2B2EF5F7851 FOREIGN KEY (id_tipo_comprobante_id) REFERENCES tipo_comprobante (id)');
        $this->addSql('ALTER TABLE registro_comprobantes ADD CONSTRAINT FK_B2D1B2B27EB2C349 FOREIGN KEY (id_usuario_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE registro_comprobantes ADD CONSTRAINT FK_B2D1B2B239161EBF FOREIGN KEY (id_almacen_id) REFERENCES almacen (id)');
        $this->addSql('ALTER TABLE saldo_cuentas ADD id_tipo_cliente INT DEFAULT NULL, ADD id_cliente INT DEFAULT NULL');
        $this->addSql('ALTER TABLE saldo_cuentas ADD CONSTRAINT FK_BB2B71AE1ADA4D3F FOREIGN KEY (id_cuenta_id) REFERENCES cuenta (id)');
        $this->addSql('ALTER TABLE saldo_cuentas ADD CONSTRAINT FK_BB2B71AE2D412F53 FOREIGN KEY (id_subcuenta_id) REFERENCES subcuenta (id)');
        $this->addSql('ALTER TABLE saldo_cuentas ADD CONSTRAINT FK_BB2B71AEC59B01FF FOREIGN KEY (id_centro_costo_id) REFERENCES centro_costo (id)');
        $this->addSql('ALTER TABLE saldo_cuentas ADD CONSTRAINT FK_BB2B71AEF66372E9 FOREIGN KEY (id_elemento_gasto_id) REFERENCES elemento_gasto (id)');
        $this->addSql('ALTER TABLE saldo_cuentas ADD CONSTRAINT FK_BB2B71AE39161EBF FOREIGN KEY (id_almacen_id) REFERENCES almacen (id)');
        $this->addSql('ALTER TABLE saldo_cuentas ADD CONSTRAINT FK_BB2B71AE1D34FA6B FOREIGN KEY (id_unidad_id) REFERENCES unidad (id)');
        $this->addSql('ALTER TABLE saldo_cuentas ADD CONSTRAINT FK_BB2B71AEE8F12801 FOREIGN KEY (id_proveedor_id) REFERENCES proveedor (id)');
        $this->addSql('ALTER TABLE saldo_cuentas ADD CONSTRAINT FK_BB2B71AEF5DBAF2B FOREIGN KEY (id_expediente_id) REFERENCES expediente (id)');
        $this->addSql('ALTER TABLE saldo_cuentas ADD CONSTRAINT FK_BB2B71AE71381BB3 FOREIGN KEY (id_orden_trabajo_id) REFERENCES orden_trabajo (id)');
        $this->addSql('ALTER TABLE subcuenta ADD CONSTRAINT FK_57BB37EA1ADA4D3F FOREIGN KEY (id_cuenta_id) REFERENCES cuenta (id)');
        $this->addSql('ALTER TABLE subcuenta_criterio_analisis ADD CONSTRAINT FK_52A4A7682D412F53 FOREIGN KEY (id_subcuenta_id) REFERENCES subcuenta (id)');
        $this->addSql('ALTER TABLE subcuenta_criterio_analisis ADD CONSTRAINT FK_52A4A7685ABBE5F6 FOREIGN KEY (id_criterio_analisis_id) REFERENCES criterio_analisis (id)');
        $this->addSql('ALTER TABLE subcuenta_proveedor ADD CONSTRAINT FK_5C22E4B82D412F53 FOREIGN KEY (id_subcuenta_id) REFERENCES subcuenta (id)');
        $this->addSql('ALTER TABLE subcuenta_proveedor ADD CONSTRAINT FK_5C22E4B8E8F12801 FOREIGN KEY (id_proveedor_id) REFERENCES proveedor (id)');
        $this->addSql('ALTER TABLE tasa_cambio ADD CONSTRAINT FK_DAB48606FA5CADE9 FOREIGN KEY (id_moneda_origen_id) REFERENCES moneda (id)');
        $this->addSql('ALTER TABLE tasa_cambio ADD CONSTRAINT FK_DAB48606D85CECF7 FOREIGN KEY (id_moneda_destino_id) REFERENCES moneda (id)');
        $this->addSql('ALTER TABLE transferencia ADD CONSTRAINT FK_EDC227306601BA07 FOREIGN KEY (id_documento_id) REFERENCES documento (id)');
        $this->addSql('ALTER TABLE transferencia ADD CONSTRAINT FK_EDC227301D34FA6B FOREIGN KEY (id_unidad_id) REFERENCES unidad (id)');
        $this->addSql('ALTER TABLE transferencia ADD CONSTRAINT FK_EDC2273039161EBF FOREIGN KEY (id_almacen_id) REFERENCES almacen (id)');
        $this->addSql('ALTER TABLE unidad ADD CONSTRAINT FK_F3E6D02F31E700CD FOREIGN KEY (id_padre_id) REFERENCES unidad (id)');
        $this->addSql('ALTER TABLE vale_salida ADD CONSTRAINT FK_90C265C86601BA07 FOREIGN KEY (id_documento_id) REFERENCES documento (id)');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE almacen_ocupado DROP FOREIGN KEY FK_AA53605839161EBF');
        $this->addSql('ALTER TABLE almacen_ocupado DROP FOREIGN KEY FK_AA5360587EB2C349');
        $this->addSql('ALTER TABLE area_responsabilidad DROP FOREIGN KEY FK_F469C2BA1D34FA6B');
        $this->addSql('ALTER TABLE asiento DROP FOREIGN KEY FK_71D6D35C1ADA4D3F');
        $this->addSql('ALTER TABLE asiento DROP FOREIGN KEY FK_71D6D35C2D412F53');
        $this->addSql('ALTER TABLE asiento DROP FOREIGN KEY FK_71D6D35C6601BA07');
        $this->addSql('ALTER TABLE asiento DROP FOREIGN KEY FK_71D6D35C39161EBF');
        $this->addSql('ALTER TABLE asiento DROP FOREIGN KEY FK_71D6D35CC59B01FF');
        $this->addSql('ALTER TABLE asiento DROP FOREIGN KEY FK_71D6D35CF66372E9');
        $this->addSql('ALTER TABLE asiento DROP FOREIGN KEY FK_71D6D35C71381BB3');
        $this->addSql('ALTER TABLE asiento DROP FOREIGN KEY FK_71D6D35CF5DBAF2B');
        $this->addSql('ALTER TABLE asiento DROP FOREIGN KEY FK_71D6D35CE8F12801');
        $this->addSql('ALTER TABLE asiento DROP FOREIGN KEY FK_71D6D35C1D34FA6B');
        $this->addSql('ALTER TABLE asiento DROP FOREIGN KEY FK_71D6D35CEF5F7851');
        $this->addSql('ALTER TABLE asiento DROP FOREIGN KEY FK_71D6D35C1800963C');
        $this->addSql('ALTER TABLE asiento DROP FOREIGN KEY FK_71D6D35C55C5F988');
        $this->addSql('DROP INDEX IDX_71D6D35CEF5F7851 ON asiento');
        $this->addSql('DROP INDEX IDX_71D6D35C1800963C ON asiento');
        $this->addSql('DROP INDEX IDX_71D6D35C55C5F988 ON asiento');
        $this->addSql('ALTER TABLE asiento DROP id_tipo_comprobante_id, DROP id_comprobante_id, DROP id_factura_id');
        $this->addSql('ALTER TABLE centro_costo DROP FOREIGN KEY FK_749608CE1D34FA6B');
        $this->addSql('ALTER TABLE cierre DROP FOREIGN KEY FK_D0DCFCC739161EBF');
        $this->addSql('ALTER TABLE cierre DROP FOREIGN KEY FK_D0DCFCC77EB2C349');
        $this->addSql('ALTER TABLE cierre_diario DROP FOREIGN KEY FK_F3D0CD8939161EBF');
        $this->addSql('ALTER TABLE cierre_diario DROP FOREIGN KEY FK_F3D0CD897EB2C349');
        $this->addSql('ALTER TABLE cobros_pagos DROP FOREIGN KEY FK_D9581D1655C5F988');
        $this->addSql('ALTER TABLE cobros_pagos DROP FOREIGN KEY FK_D9581D1626990C38');
        $this->addSql('ALTER TABLE cobros_pagos DROP FOREIGN KEY FK_D9581D16E8F12801');
        $this->addSql('ALTER TABLE comprobante_cierre DROP FOREIGN KEY FK_D03EA4C51800963C');
        $this->addSql('ALTER TABLE comprobante_cierre DROP FOREIGN KEY FK_D03EA4C545F8C94C');
        $this->addSql('ALTER TABLE configuracion_inicial DROP FOREIGN KEY FK_8521BE24404AE9D2');
        $this->addSql('ALTER TABLE configuracion_inicial DROP FOREIGN KEY FK_8521BE247A4F962');
        $this->addSql('ALTER TABLE contratos_cliente DROP FOREIGN KEY FK_29A5BB477BF9CE86');
        $this->addSql('ALTER TABLE contratos_cliente DROP FOREIGN KEY FK_29A5BB47374388F5');
        $this->addSql('ALTER TABLE cuadre_diario DROP FOREIGN KEY FK_60ABEFD91ADA4D3F');
        $this->addSql('ALTER TABLE cuadre_diario DROP FOREIGN KEY FK_60ABEFD92D412F53');
        $this->addSql('ALTER TABLE cuadre_diario DROP FOREIGN KEY FK_60ABEFD945F8C94C');
        $this->addSql('ALTER TABLE cuadre_diario DROP FOREIGN KEY FK_60ABEFD939161EBF');
        $this->addSql('ALTER TABLE cuenta DROP FOREIGN KEY FK_31C7BFCF45E7F350');
        $this->addSql('ALTER TABLE cuenta_criterio_analisis DROP FOREIGN KEY FK_AF040B091ADA4D3F');
        $this->addSql('ALTER TABLE cuenta_criterio_analisis DROP FOREIGN KEY FK_AF040B095ABBE5F6');
        $this->addSql('ALTER TABLE cuentas_cliente DROP FOREIGN KEY FK_64653310374388F5');
        $this->addSql('ALTER TABLE cuentas_cliente DROP FOREIGN KEY FK_646533107BF9CE86');
        $this->addSql('ALTER TABLE custom_user DROP FOREIGN KEY FK_8CE51EB479F37AE5');
        $this->addSql('ALTER TABLE depreciacion DROP FOREIGN KEY FK_D618AE145832E72E');
        $this->addSql('ALTER TABLE devolucion DROP FOREIGN KEY FK_524D9F676601BA07');
        $this->addSql('ALTER TABLE devolucion DROP FOREIGN KEY FK_524D9F671D34FA6B');
        $this->addSql('ALTER TABLE devolucion DROP FOREIGN KEY FK_524D9F6739161EBF');
        $this->addSql('ALTER TABLE devolucion DROP FOREIGN KEY FK_524D9F67C59B01FF');
        $this->addSql('ALTER TABLE devolucion DROP FOREIGN KEY FK_524D9F67F66372E9');
        $this->addSql('ALTER TABLE devolucion DROP FOREIGN KEY FK_524D9F675074DD86');
        $this->addSql('ALTER TABLE documento DROP FOREIGN KEY FK_B6B12EC739161EBF');
        $this->addSql('ALTER TABLE documento DROP FOREIGN KEY FK_B6B12EC71D34FA6B');
        $this->addSql('ALTER TABLE documento DROP FOREIGN KEY FK_B6B12EC7374388F5');
        $this->addSql('ALTER TABLE documento DROP FOREIGN KEY FK_B6B12EC77A4F962');
        $this->addSql('ALTER TABLE documento DROP FOREIGN KEY FK_B6B12EC74832F387');
        $this->addSql('ALTER TABLE empleado DROP FOREIGN KEY FK_D9D9BF521D34FA6B');
        $this->addSql('ALTER TABLE empleado DROP FOREIGN KEY FK_D9D9BF52D1E12F15');
        $this->addSql('ALTER TABLE empleado DROP FOREIGN KEY FK_D9D9BF527EB2C349');
        $this->addSql('ALTER TABLE expediente DROP FOREIGN KEY FK_D59CA4131D34FA6B');
        $this->addSql('ALTER TABLE factura DROP FOREIGN KEY FK_F9EBA00968BCB606');
        $this->addSql('ALTER TABLE factura DROP FOREIGN KEY FK_F9EBA0091D34FA6B');
        $this->addSql('ALTER TABLE factura DROP FOREIGN KEY FK_F9EBA0097EB2C349');
        $this->addSql('ALTER TABLE factura DROP FOREIGN KEY FK_F9EBA009C59B01FF');
        $this->addSql('ALTER TABLE factura DROP FOREIGN KEY FK_F9EBA00971381BB3');
        $this->addSql('ALTER TABLE factura DROP FOREIGN KEY FK_F9EBA009F66372E9');
        $this->addSql('ALTER TABLE factura DROP FOREIGN KEY FK_F9EBA009F5DBAF2B');
        $this->addSql('ALTER TABLE factura DROP FOREIGN KEY FK_F9EBA0094F4C4E26');
        $this->addSql('ALTER TABLE factura DROP FOREIGN KEY FK_F9EBA009C37A5552');
        $this->addSql('ALTER TABLE factura DROP FOREIGN KEY FK_F9EBA009374388F5');
        $this->addSql('ALTER TABLE factura DROP FOREIGN KEY FK_F9EBA00999274826');
        $this->addSql('ALTER TABLE factura_documento DROP FOREIGN KEY FK_CCC060C155C5F988');
        $this->addSql('ALTER TABLE factura_documento DROP FOREIGN KEY FK_CCC060C16601BA07');
        $this->addSql('ALTER TABLE factura_documento DROP FOREIGN KEY FK_CCC060C1EC34F77F');
        $this->addSql('ALTER TABLE facturas_comprobante DROP FOREIGN KEY FK_6FD2F19B55C5F988');
        $this->addSql('ALTER TABLE facturas_comprobante DROP FOREIGN KEY FK_6FD2F19B1800963C');
        $this->addSql('ALTER TABLE facturas_comprobante DROP FOREIGN KEY FK_6FD2F19B1D34FA6B');
        $this->addSql('ALTER TABLE informe_recepcion DROP FOREIGN KEY FK_62A4EBD6601BA07');
        $this->addSql('ALTER TABLE informe_recepcion DROP FOREIGN KEY FK_62A4EBDE8F12801');
        $this->addSql('ALTER TABLE mercancia DROP FOREIGN KEY FK_9D094AE0E2C70A62');
        $this->addSql('ALTER TABLE mercancia DROP FOREIGN KEY FK_9D094AE0E16A5625');
        $this->addSql('ALTER TABLE mercancia_producto DROP FOREIGN KEY FK_3F705CF59F287F54');
        $this->addSql('ALTER TABLE mercancia_producto DROP FOREIGN KEY FK_3F705CF56E57A479');
        $this->addSql('ALTER TABLE movimiento DROP FOREIGN KEY FK_C8FF107AD1CE493D');
        $this->addSql('ALTER TABLE movimiento DROP FOREIGN KEY FK_C8FF107ADB763453');
        $this->addSql('ALTER TABLE movimiento DROP FOREIGN KEY FK_C8FF107A873C7FC7');
        $this->addSql('ALTER TABLE movimiento DROP FOREIGN KEY FK_C8FF107A4F781EA');
        $this->addSql('ALTER TABLE movimiento_activo_fijo DROP FOREIGN KEY FK_A985A0DA1D34FA6B');
        $this->addSql('ALTER TABLE movimiento_activo_fijo DROP FOREIGN KEY FK_A985A0DA5832E72E');
        $this->addSql('ALTER TABLE movimiento_activo_fijo DROP FOREIGN KEY FK_A985A0DADB763453');
        $this->addSql('ALTER TABLE movimiento_activo_fijo DROP FOREIGN KEY FK_A985A0DA1ADA4D3F');
        $this->addSql('ALTER TABLE movimiento_activo_fijo DROP FOREIGN KEY FK_A985A0DA2D412F53');
        $this->addSql('ALTER TABLE movimiento_activo_fijo DROP FOREIGN KEY FK_A985A0DA7EB2C349');
        $this->addSql('ALTER TABLE movimiento_mercancia DROP FOREIGN KEY FK_44876BD79F287F54');
        $this->addSql('ALTER TABLE movimiento_mercancia DROP FOREIGN KEY FK_44876BD76601BA07');
        $this->addSql('ALTER TABLE movimiento_mercancia DROP FOREIGN KEY FK_44876BD77A4F962');
        $this->addSql('ALTER TABLE movimiento_mercancia DROP FOREIGN KEY FK_44876BD77EB2C349');
        $this->addSql('ALTER TABLE movimiento_mercancia DROP FOREIGN KEY FK_44876BD7C59B01FF');
        $this->addSql('ALTER TABLE movimiento_mercancia DROP FOREIGN KEY FK_44876BD7F66372E9');
        $this->addSql('ALTER TABLE movimiento_mercancia DROP FOREIGN KEY FK_44876BD739161EBF');
        $this->addSql('ALTER TABLE movimiento_mercancia DROP FOREIGN KEY FK_44876BD7F5DBAF2B');
        $this->addSql('ALTER TABLE movimiento_mercancia DROP FOREIGN KEY FK_44876BD771381BB3');
        $this->addSql('ALTER TABLE movimiento_mercancia DROP FOREIGN KEY FK_44876BD755C5F988');
        $this->addSql('ALTER TABLE movimiento_mercancia DROP FOREIGN KEY FK_44876BD7571159DE');
        $this->addSql('ALTER TABLE movimiento_producto DROP FOREIGN KEY FK_FFC0EDFC6E57A479');
        $this->addSql('ALTER TABLE movimiento_producto DROP FOREIGN KEY FK_FFC0EDFC6601BA07');
        $this->addSql('ALTER TABLE movimiento_producto DROP FOREIGN KEY FK_FFC0EDFC7A4F962');
        $this->addSql('ALTER TABLE movimiento_producto DROP FOREIGN KEY FK_FFC0EDFC7EB2C349');
        $this->addSql('ALTER TABLE movimiento_producto DROP FOREIGN KEY FK_FFC0EDFCC59B01FF');
        $this->addSql('ALTER TABLE movimiento_producto DROP FOREIGN KEY FK_FFC0EDFCF66372E9');
        $this->addSql('ALTER TABLE movimiento_producto DROP FOREIGN KEY FK_FFC0EDFC39161EBF');
        $this->addSql('ALTER TABLE movimiento_producto DROP FOREIGN KEY FK_FFC0EDFC71381BB3');
        $this->addSql('ALTER TABLE movimiento_producto DROP FOREIGN KEY FK_FFC0EDFCF5DBAF2B');
        $this->addSql('ALTER TABLE movimiento_producto DROP FOREIGN KEY FK_FFC0EDFC55C5F988');
        $this->addSql('ALTER TABLE movimiento_producto DROP FOREIGN KEY FK_FFC0EDFC571159DE');
        $this->addSql('DROP INDEX IDX_FFC0EDFC571159DE ON movimiento_producto');
        $this->addSql('ALTER TABLE movimiento_producto DROP id_movimiento_cancelado_id');
        $this->addSql('ALTER TABLE movimiento_servicio DROP FOREIGN KEY FK_93FD19C355C5F988');
        $this->addSql('ALTER TABLE movimiento_servicio DROP FOREIGN KEY FK_93FD19C371CAA3E7');
        $this->addSql('ALTER TABLE movimiento_venta DROP FOREIGN KEY FK_8E3F7AE555C5F988');
        $this->addSql('ALTER TABLE movimiento_venta DROP FOREIGN KEY FK_8E3F7AE539161EBF');
        $this->addSql('ALTER TABLE movimiento_venta DROP FOREIGN KEY FK_8E3F7AE5D8F8B0AD');
        $this->addSql('ALTER TABLE movimiento_venta DROP FOREIGN KEY FK_8E3F7AE5FA3DF5CD');
        $this->addSql('ALTER TABLE movimiento_venta DROP FOREIGN KEY FK_8E3F7AE5F0821C98');
        $this->addSql('ALTER TABLE movimiento_venta DROP FOREIGN KEY FK_8E3F7AE56EA527F2');
        $this->addSql('ALTER TABLE obligacion_cobro DROP FOREIGN KEY FK_807C726D55C5F988');
        $this->addSql('ALTER TABLE obligacion_pago DROP FOREIGN KEY FK_403C9B3BE8F12801');
        $this->addSql('ALTER TABLE obligacion_pago DROP FOREIGN KEY FK_403C9B3B6601BA07');
        $this->addSql('ALTER TABLE obligacion_pago DROP FOREIGN KEY FK_403C9B3B1D34FA6B');
        $this->addSql('ALTER TABLE operaciones_comprobante_operaciones DROP FOREIGN KEY FK_E7EA17E1ADA4D3F');
        $this->addSql('ALTER TABLE operaciones_comprobante_operaciones DROP FOREIGN KEY FK_E7EA17E2D412F53');
        $this->addSql('ALTER TABLE operaciones_comprobante_operaciones DROP FOREIGN KEY FK_E7EA17EC59B01FF');
        $this->addSql('ALTER TABLE operaciones_comprobante_operaciones DROP FOREIGN KEY FK_E7EA17E71381BB3');
        $this->addSql('ALTER TABLE operaciones_comprobante_operaciones DROP FOREIGN KEY FK_E7EA17EF66372E9');
        $this->addSql('ALTER TABLE operaciones_comprobante_operaciones DROP FOREIGN KEY FK_E7EA17EF5DBAF2B');
        $this->addSql('ALTER TABLE operaciones_comprobante_operaciones DROP FOREIGN KEY FK_E7EA17EE8F12801');
        $this->addSql('ALTER TABLE operaciones_comprobante_operaciones DROP FOREIGN KEY FK_E7EA17EECB9FBA7');
        $this->addSql('ALTER TABLE operaciones_comprobante_operaciones DROP FOREIGN KEY FK_E7EA17E39161EBF');
        $this->addSql('ALTER TABLE operaciones_comprobante_operaciones DROP FOREIGN KEY FK_E7EA17E1D34FA6B');
        $this->addSql('ALTER TABLE orden_trabajo DROP FOREIGN KEY FK_4158A0241D34FA6B');
        $this->addSql('ALTER TABLE orden_trabajo DROP FOREIGN KEY FK_4158A02439161EBF');
        $this->addSql('ALTER TABLE producto DROP FOREIGN KEY FK_A7BB0615E2C70A62');
        $this->addSql('ALTER TABLE producto DROP FOREIGN KEY FK_A7BB0615E16A5625');
        $this->addSql('ALTER TABLE registro_comprobantes DROP FOREIGN KEY FK_B2D1B2B21D34FA6B');
        $this->addSql('ALTER TABLE registro_comprobantes DROP FOREIGN KEY FK_B2D1B2B2EF5F7851');
        $this->addSql('ALTER TABLE registro_comprobantes DROP FOREIGN KEY FK_B2D1B2B27EB2C349');
        $this->addSql('ALTER TABLE registro_comprobantes DROP FOREIGN KEY FK_B2D1B2B239161EBF');
        $this->addSql('ALTER TABLE saldo_cuentas DROP FOREIGN KEY FK_BB2B71AE1ADA4D3F');
        $this->addSql('ALTER TABLE saldo_cuentas DROP FOREIGN KEY FK_BB2B71AE2D412F53');
        $this->addSql('ALTER TABLE saldo_cuentas DROP FOREIGN KEY FK_BB2B71AEC59B01FF');
        $this->addSql('ALTER TABLE saldo_cuentas DROP FOREIGN KEY FK_BB2B71AEF66372E9');
        $this->addSql('ALTER TABLE saldo_cuentas DROP FOREIGN KEY FK_BB2B71AE39161EBF');
        $this->addSql('ALTER TABLE saldo_cuentas DROP FOREIGN KEY FK_BB2B71AE1D34FA6B');
        $this->addSql('ALTER TABLE saldo_cuentas DROP FOREIGN KEY FK_BB2B71AEE8F12801');
        $this->addSql('ALTER TABLE saldo_cuentas DROP FOREIGN KEY FK_BB2B71AEF5DBAF2B');
        $this->addSql('ALTER TABLE saldo_cuentas DROP FOREIGN KEY FK_BB2B71AE71381BB3');
        $this->addSql('ALTER TABLE saldo_cuentas DROP id_tipo_cliente, DROP id_cliente');
        $this->addSql('ALTER TABLE subcuenta DROP FOREIGN KEY FK_57BB37EA1ADA4D3F');
        $this->addSql('ALTER TABLE subcuenta_criterio_analisis DROP FOREIGN KEY FK_52A4A7682D412F53');
        $this->addSql('ALTER TABLE subcuenta_criterio_analisis DROP FOREIGN KEY FK_52A4A7685ABBE5F6');
        $this->addSql('ALTER TABLE subcuenta_proveedor DROP FOREIGN KEY FK_5C22E4B82D412F53');
        $this->addSql('ALTER TABLE subcuenta_proveedor DROP FOREIGN KEY FK_5C22E4B8E8F12801');
        $this->addSql('ALTER TABLE tasa_cambio DROP FOREIGN KEY FK_DAB48606FA5CADE9');
        $this->addSql('ALTER TABLE tasa_cambio DROP FOREIGN KEY FK_DAB48606D85CECF7');
        $this->addSql('ALTER TABLE transferencia DROP FOREIGN KEY FK_EDC227306601BA07');
        $this->addSql('ALTER TABLE transferencia DROP FOREIGN KEY FK_EDC227301D34FA6B');
        $this->addSql('ALTER TABLE transferencia DROP FOREIGN KEY FK_EDC2273039161EBF');
        $this->addSql('ALTER TABLE unidad DROP FOREIGN KEY FK_F3E6D02F31E700CD');
        $this->addSql('ALTER TABLE vale_salida DROP FOREIGN KEY FK_90C265C86601BA07');
    }
}
