<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20201130140310 extends AbstractMigration
{
    public function getDescription() : string
    {
        return '';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE activo_fijo (id INT AUTO_INCREMENT NOT NULL, id_tipo_movimiento_id INT DEFAULT NULL, id_tipo_movimiento_baja_id INT DEFAULT NULL, id_area_responsabilidad_id INT NOT NULL, id_grupo_activo_id INT NOT NULL, id_unidad_id INT NOT NULL, nro_inventario VARCHAR(255) NOT NULL, nro_consecutivo INT NOT NULL, fecha_alta DATE NOT NULL, nro_documento_baja INT DEFAULT NULL, fecha_baja DATE DEFAULT NULL, descripcion VARCHAR(255) NOT NULL, valor_inicial DOUBLE PRECISION NOT NULL, depreciacion_acumulada DOUBLE PRECISION DEFAULT NULL, valor_real DOUBLE PRECISION DEFAULT NULL, annos_vida_util DOUBLE PRECISION NOT NULL, pais VARCHAR(255) DEFAULT NULL, modelo VARCHAR(255) DEFAULT NULL, tipo VARCHAR(255) DEFAULT NULL, marca VARCHAR(255) DEFAULT NULL, nro_motor VARCHAR(255) DEFAULT NULL, nro_serie VARCHAR(255) DEFAULT NULL, nro_chapa VARCHAR(255) DEFAULT NULL, nro_chasis VARCHAR(255) DEFAULT NULL, combustible VARCHAR(255) DEFAULT NULL, activo TINYINT(1) NOT NULL, fecha_ultima_depreciacion DATE DEFAULT NULL, INDEX IDX_75EBC93EDB763453 (id_tipo_movimiento_id), INDEX IDX_75EBC93E6FBA0327 (id_tipo_movimiento_baja_id), INDEX IDX_75EBC93ED410562 (id_area_responsabilidad_id), INDEX IDX_75EBC93E4A667A2B (id_grupo_activo_id), INDEX IDX_75EBC93E1D34FA6B (id_unidad_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE activo_fijo_cuentas (id INT AUTO_INCREMENT NOT NULL, id_activo_id INT NOT NULL, id_cuenta_activo_id INT NOT NULL, id_subcuenta_activo_id INT NOT NULL, id_centro_costo_activo_id INT NOT NULL, id_area_responsabilidad_activo_id INT NOT NULL, id_cuenta_depreciacion_id INT NOT NULL, id_subcuenta_depreciacion_id INT NOT NULL, id_cuenta_gasto_id INT NOT NULL, id_subcuenta_gasto_id INT NOT NULL, id_centro_costo_gasto_id INT NOT NULL, id_elemento_gasto_gasto_id INT NOT NULL, INDEX IDX_E0DF2901C84BDE84 (id_activo_id), INDEX IDX_E0DF290186762CC7 (id_cuenta_activo_id), INDEX IDX_E0DF29014476721E (id_subcuenta_activo_id), INDEX IDX_E0DF29012955A16D (id_centro_costo_activo_id), INDEX IDX_E0DF29014C675596 (id_area_responsabilidad_activo_id), INDEX IDX_E0DF290174A5FFBA (id_cuenta_depreciacion_id), INDEX IDX_E0DF2901549C81D9 (id_subcuenta_depreciacion_id), INDEX IDX_E0DF290180C608FA (id_cuenta_gasto_id), INDEX IDX_E0DF290157677646 (id_subcuenta_gasto_id), INDEX IDX_E0DF2901A950EE53 (id_centro_costo_gasto_id), INDEX IDX_E0DF2901A752F04B (id_elemento_gasto_gasto_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE activo_fijo_movimiento_activo_fijo (id INT AUTO_INCREMENT NOT NULL, id_activo_fijo_id INT NOT NULL, id_movimiento_activo_fijo_id INT NOT NULL, INDEX IDX_2FA61FF25832E72E (id_activo_fijo_id), INDEX IDX_2FA61FF27786CA71 (id_movimiento_activo_fijo_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ajuste (id INT AUTO_INCREMENT NOT NULL, id_documento_id INT NOT NULL, nro_cuenta_inventario VARCHAR(255) NOT NULL, observacion VARCHAR(255) NOT NULL, nro_subcuenta_inventario VARCHAR(255) NOT NULL, nro_cuenta_acreedora VARCHAR(255) NOT NULL, nro_subcuenta_acreedora VARCHAR(255) NOT NULL, nro_concecutivo VARCHAR(255) NOT NULL, anno INT NOT NULL, activo TINYINT(1) NOT NULL, entrada TINYINT(1) NOT NULL, INDEX IDX_DD35BD326601BA07 (id_documento_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE almacen (id INT AUTO_INCREMENT NOT NULL, id_unidad_id INT NOT NULL, descripcion VARCHAR(255) NOT NULL, activo TINYINT(1) NOT NULL, codigo VARCHAR(255) DEFAULT NULL, UNIQUE INDEX UNIQ_D5B2D25020332D99 (codigo), INDEX IDX_D5B2D2501D34FA6B (id_unidad_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE almacen_ocupado (id INT AUTO_INCREMENT NOT NULL, id_almacen_id INT NOT NULL, id_usuario_id INT NOT NULL, INDEX IDX_AA53605839161EBF (id_almacen_id), INDEX IDX_AA5360587EB2C349 (id_usuario_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE area_responsabilidad (id INT AUTO_INCREMENT NOT NULL, id_unidad_id INT NOT NULL, codigo VARCHAR(255) NOT NULL, nombre VARCHAR(255) NOT NULL, activo TINYINT(1) NOT NULL, INDEX IDX_F469C2BA1D34FA6B (id_unidad_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cargo (id INT AUTO_INCREMENT NOT NULL, nombre VARCHAR(255) NOT NULL, salario_base DOUBLE PRECISION NOT NULL, activo TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE carrito (id INT AUTO_INCREMENT NOT NULL, json VARCHAR(1500) NOT NULL, empleado VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE centro_costo (id INT AUTO_INCREMENT NOT NULL, id_unidad_id INT NOT NULL, activo TINYINT(1) NOT NULL, codigo VARCHAR(255) NOT NULL, nombre VARCHAR(255) NOT NULL, INDEX IDX_749608CE1D34FA6B (id_unidad_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cierre (id INT AUTO_INCREMENT NOT NULL, id_almacen_id INT NOT NULL, id_usuario_id INT DEFAULT NULL, diario TINYINT(1) NOT NULL, mes INT DEFAULT NULL, anno INT NOT NULL, fecha DATE NOT NULL, saldo DOUBLE PRECISION NOT NULL, abierto TINYINT(1) DEFAULT NULL, debito DOUBLE PRECISION NOT NULL, credito DOUBLE PRECISION NOT NULL, INDEX IDX_D0DCFCC739161EBF (id_almacen_id), INDEX IDX_D0DCFCC77EB2C349 (id_usuario_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cierre_diario (id INT AUTO_INCREMENT NOT NULL, id_almacen_id INT NOT NULL, id_usuario_id INT NOT NULL, fecha_cerrado DATE NOT NULL, fecha_cerrado_real DATETIME NOT NULL, INDEX IDX_F3D0CD8939161EBF (id_almacen_id), INDEX IDX_F3D0CD897EB2C349 (id_usuario_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cliente (id INT AUTO_INCREMENT NOT NULL, nombre VARCHAR(255) NOT NULL, apellidos VARCHAR(255) DEFAULT NULL, correo VARCHAR(255) DEFAULT NULL, direccion VARCHAR(255) DEFAULT NULL, token VARCHAR(255) DEFAULT NULL, fecha DATE DEFAULT NULL, usuario INT DEFAULT NULL, comentario VARCHAR(255) DEFAULT NULL, telefono VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cliente_beneficiario (id INT AUTO_INCREMENT NOT NULL, id_cliente VARCHAR(255) NOT NULL, primer_nombre VARCHAR(255) NOT NULL, telefono_casa VARCHAR(255) DEFAULT NULL, primer_apellido VARCHAR(255) NOT NULL, segundo_apellido VARCHAR(255) DEFAULT NULL, alternativo_nombre VARCHAR(255) DEFAULT NULL, alternativo_apellido VARCHAR(255) DEFAULT NULL, alternativo_segundo_apellido VARCHAR(255) DEFAULT NULL, telefono VARCHAR(255) NOT NULL, identificacion VARCHAR(255) DEFAULT NULL, calle VARCHAR(255) NOT NULL, no VARCHAR(255) NOT NULL, entre VARCHAR(255) DEFAULT NULL, y VARCHAR(255) DEFAULT NULL, apto VARCHAR(255) DEFAULT NULL, edificio VARCHAR(255) DEFAULT NULL, reparto VARCHAR(255) DEFAULT NULL, provincia VARCHAR(255) DEFAULT NULL, municipio VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cliente_contabilidad (id INT AUTO_INCREMENT NOT NULL, codigo VARCHAR(255) NOT NULL, nombre VARCHAR(255) NOT NULL, direccion VARCHAR(255) NOT NULL, telefonos VARCHAR(255) NOT NULL, fax VARCHAR(255) DEFAULT NULL, correos VARCHAR(255) NOT NULL, activo TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cliente_reporte (id INT AUTO_INCREMENT NOT NULL, user VARCHAR(255) NOT NULL, fecha DATETIME NOT NULL, id_cliente VARCHAR(255) NOT NULL, bram VARCHAR(255) NOT NULL, last4 VARCHAR(255) NOT NULL, monto VARCHAR(255) NOT NULL, comercio VARCHAR(255) NOT NULL, estado VARCHAR(255) NOT NULL, auth VARCHAR(255) NOT NULL, efectivo VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE comprobante_cierre (id INT AUTO_INCREMENT NOT NULL, id_comprobante_id INT NOT NULL, id_cierre_id INT NOT NULL, INDEX IDX_D03EA4C51800963C (id_comprobante_id), INDEX IDX_D03EA4C545F8C94C (id_cierre_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE configuracion_inicial (id INT AUTO_INCREMENT NOT NULL, id_modulo_id INT NOT NULL, id_tipo_documento_id INT NOT NULL, deudora TINYINT(1) NOT NULL, activo TINYINT(1) NOT NULL, str_cuentas VARCHAR(255) NOT NULL, str_subcuentas VARCHAR(255) NOT NULL, str_elemento_gasto VARCHAR(255) NOT NULL, str_cuentas_contrapartida VARCHAR(255) NOT NULL, str_subcuentas_contrapartida VARCHAR(255) DEFAULT NULL, INDEX IDX_8521BE24404AE9D2 (id_modulo_id), INDEX IDX_8521BE247A4F962 (id_tipo_documento_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE contratos_cliente (id INT AUTO_INCREMENT NOT NULL, id_cliente_id INT NOT NULL, id_moneda_id INT NOT NULL, nro_contrato VARCHAR(255) NOT NULL, anno INT NOT NULL, fecha_aprobado DATE NOT NULL, fecha_vencimiento DATE DEFAULT NULL, activo TINYINT(1) NOT NULL, importe DOUBLE PRECISION NOT NULL, resto DOUBLE PRECISION DEFAULT NULL, id_padre INT DEFAULT NULL, INDEX IDX_29A5BB477BF9CE86 (id_cliente_id), INDEX IDX_29A5BB47374388F5 (id_moneda_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE criterio_analisis (id INT AUTO_INCREMENT NOT NULL, nombre VARCHAR(255) NOT NULL, abreviatura VARCHAR(255) NOT NULL, activo TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cuadre_diario (id INT AUTO_INCREMENT NOT NULL, id_cuenta_id INT NOT NULL, id_subcuenta_id INT NOT NULL, id_cierre_id INT NOT NULL, id_almacen_id INT NOT NULL, str_analisis VARCHAR(255) DEFAULT NULL, fecha DATE NOT NULL, saldo NUMERIC(10, 2) NOT NULL, debito DOUBLE PRECISION NOT NULL, credito DOUBLE PRECISION NOT NULL, INDEX IDX_60ABEFD91ADA4D3F (id_cuenta_id), INDEX IDX_60ABEFD92D412F53 (id_subcuenta_id), INDEX IDX_60ABEFD945F8C94C (id_cierre_id), INDEX IDX_60ABEFD939161EBF (id_almacen_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cuenta (id INT AUTO_INCREMENT NOT NULL, id_tipo_cuenta_id INT NOT NULL, nro_cuenta INT NOT NULL, nombre VARCHAR(255) NOT NULL, deudora TINYINT(1) NOT NULL, mixta TINYINT(1) NOT NULL, obligacion_deudora TINYINT(1) NOT NULL, obligacion_acreedora TINYINT(1) NOT NULL, activo TINYINT(1) NOT NULL, produccion TINYINT(1) NOT NULL, INDEX IDX_31C7BFCF45E7F350 (id_tipo_cuenta_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cuenta_criterio_analisis (id INT AUTO_INCREMENT NOT NULL, id_cuenta_id INT NOT NULL, id_criterio_analisis_id INT NOT NULL, orden INT DEFAULT NULL, INDEX IDX_AF040B091ADA4D3F (id_cuenta_id), INDEX IDX_AF040B095ABBE5F6 (id_criterio_analisis_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cuentas_cliente (id INT AUTO_INCREMENT NOT NULL, id_moneda_id INT NOT NULL, id_cliente_id INT NOT NULL, nro_cuenta VARCHAR(255) NOT NULL, activo TINYINT(1) NOT NULL, INDEX IDX_64653310374388F5 (id_moneda_id), INDEX IDX_646533107BF9CE86 (id_cliente_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE custom_user (id INT AUTO_INCREMENT NOT NULL, id_user_id INT NOT NULL, nombre_completo VARCHAR(255) NOT NULL, correo VARCHAR(255) DEFAULT NULL, UNIQUE INDEX UNIQ_8CE51EB479F37AE5 (id_user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE depreciacion (id INT AUTO_INCREMENT NOT NULL, id_activo_fijo_id INT NOT NULL, fecha DATE NOT NULL, anno INT NOT NULL, mes INT NOT NULL, importe_depreciacion DOUBLE PRECISION NOT NULL, INDEX IDX_D618AE145832E72E (id_activo_fijo_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE devolucion (id INT AUTO_INCREMENT NOT NULL, id_documento_id INT DEFAULT NULL, id_unidad_id INT NOT NULL, id_almacen_id INT NOT NULL, id_centro_costo_id INT DEFAULT NULL, id_elemento_gasto_id INT DEFAULT NULL, id_orden_tabajo_id INT DEFAULT NULL, nro_cuenta VARCHAR(255) NOT NULL, nro_subcuenta VARCHAR(255) NOT NULL, anno INT NOT NULL, activo TINYINT(1) NOT NULL, nro_concecutivo VARCHAR(255) NOT NULL, INDEX IDX_524D9F676601BA07 (id_documento_id), INDEX IDX_524D9F671D34FA6B (id_unidad_id), INDEX IDX_524D9F6739161EBF (id_almacen_id), INDEX IDX_524D9F67C59B01FF (id_centro_costo_id), INDEX IDX_524D9F67F66372E9 (id_elemento_gasto_id), INDEX IDX_524D9F675074DD86 (id_orden_tabajo_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE documento (id INT AUTO_INCREMENT NOT NULL, id_almacen_id INT NOT NULL, id_unidad_id INT NOT NULL, id_moneda_id INT NOT NULL, id_tipo_documento_id INT DEFAULT NULL, importe_total DOUBLE PRECISION NOT NULL, fecha DATE NOT NULL, activo TINYINT(1) NOT NULL, anno INT DEFAULT NULL, INDEX IDX_B6B12EC739161EBF (id_almacen_id), INDEX IDX_B6B12EC71D34FA6B (id_unidad_id), INDEX IDX_B6B12EC7374388F5 (id_moneda_id), INDEX IDX_B6B12EC77A4F962 (id_tipo_documento_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE elemento_gasto (id INT AUTO_INCREMENT NOT NULL, codigo VARCHAR(255) NOT NULL, descripcion VARCHAR(255) NOT NULL, activo TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE empleado (id INT AUTO_INCREMENT NOT NULL, id_unidad_id INT NOT NULL, id_cargo_id INT DEFAULT NULL, id_usuario_id INT DEFAULT NULL, nombre VARCHAR(255) NOT NULL, correo VARCHAR(255) DEFAULT NULL, salario_x_hora DOUBLE PRECISION DEFAULT NULL, fecha_alta DATE DEFAULT NULL, baja TINYINT(1) NOT NULL, fecha_baja DATE DEFAULT NULL, direccion_particular VARCHAR(255) DEFAULT NULL, telefono VARCHAR(255) DEFAULT NULL, acumulado_tiempo_vacaciones DOUBLE PRECISION DEFAULT NULL, acumulado_dinero_vacaciones DOUBLE PRECISION DEFAULT NULL, rol VARCHAR(255) DEFAULT NULL, activo TINYINT(1) NOT NULL, INDEX IDX_D9D9BF521D34FA6B (id_unidad_id), INDEX IDX_D9D9BF52D1E12F15 (id_cargo_id), UNIQUE INDEX UNIQ_D9D9BF527EB2C349 (id_usuario_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE expediente (id INT AUTO_INCREMENT NOT NULL, id_unidad_id INT DEFAULT NULL, codigo VARCHAR(255) NOT NULL, descripcion VARCHAR(255) NOT NULL, activo TINYINT(1) NOT NULL, anno INT NOT NULL, INDEX IDX_D59CA4131D34FA6B (id_unidad_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE factura (id INT AUTO_INCREMENT NOT NULL, id_contrato_id INT DEFAULT NULL, id_unidad_id INT NOT NULL, id_usuario_id INT NOT NULL, id_centro_costo_id INT DEFAULT NULL, id_orden_trabajo_id INT DEFAULT NULL, id_elemento_gasto_id INT DEFAULT NULL, id_expediente_id INT DEFAULT NULL, fecha_factura DATE NOT NULL, tipo_cliente INT NOT NULL, id_cliente INT NOT NULL, nro_factura INT NOT NULL, anno INT NOT NULL, cuenta_obligacion VARCHAR(255) DEFAULT NULL, subcuenta_obligacion VARCHAR(255) DEFAULT NULL, activo TINYINT(1) NOT NULL, importe DOUBLE PRECISION NOT NULL, contabilizada TINYINT(1) DEFAULT NULL, ncf VARCHAR(255) DEFAULT NULL, INDEX IDX_F9EBA00968BCB606 (id_contrato_id), INDEX IDX_F9EBA0091D34FA6B (id_unidad_id), INDEX IDX_F9EBA0097EB2C349 (id_usuario_id), INDEX IDX_F9EBA009C59B01FF (id_centro_costo_id), INDEX IDX_F9EBA00971381BB3 (id_orden_trabajo_id), INDEX IDX_F9EBA009F66372E9 (id_elemento_gasto_id), INDEX IDX_F9EBA009F5DBAF2B (id_expediente_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE factura_documento (id INT AUTO_INCREMENT NOT NULL, id_factura_id INT NOT NULL, id_documento_id INT NOT NULL, id_movimiento_venta_id INT DEFAULT NULL, INDEX IDX_CCC060C155C5F988 (id_factura_id), INDEX IDX_CCC060C16601BA07 (id_documento_id), INDEX IDX_CCC060C1EC34F77F (id_movimiento_venta_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE facturas_comprobante (id INT AUTO_INCREMENT NOT NULL, id_factura_id INT NOT NULL, id_comprobante_id INT NOT NULL, id_unidad_id INT NOT NULL, anno INT NOT NULL, INDEX IDX_6FD2F19B55C5F988 (id_factura_id), INDEX IDX_6FD2F19B1800963C (id_comprobante_id), INDEX IDX_6FD2F19B1D34FA6B (id_unidad_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE grupo_activos (id INT AUTO_INCREMENT NOT NULL, porciento_deprecia_anno DOUBLE PRECISION NOT NULL, descripcion VARCHAR(255) NOT NULL, activo TINYINT(1) NOT NULL, codigo VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE informe_recepcion (id INT AUTO_INCREMENT NOT NULL, id_documento_id INT NOT NULL, id_proveedor_id INT DEFAULT NULL, nro_cuenta_inventario VARCHAR(255) NOT NULL, nro_subcuenta_inventario VARCHAR(255) NOT NULL, nro_cuenta_acreedora VARCHAR(255) NOT NULL, nro_subcuenta_acreedora VARCHAR(255) NOT NULL, nro_concecutivo VARCHAR(255) NOT NULL, anno INT NOT NULL, codigo_factura VARCHAR(255) DEFAULT NULL, fecha_factura DATE DEFAULT NULL, activo TINYINT(1) NOT NULL, producto TINYINT(1) DEFAULT NULL, INDEX IDX_62A4EBD6601BA07 (id_documento_id), INDEX IDX_62A4EBDE8F12801 (id_proveedor_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE instrumento_cobro (id INT AUTO_INCREMENT NOT NULL, nombre VARCHAR(255) NOT NULL, activo TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE mercancia (id INT AUTO_INCREMENT NOT NULL, id_amlacen_id INT NOT NULL, id_unidad_medida_id INT NOT NULL, codigo VARCHAR(255) NOT NULL, cuenta VARCHAR(255) NOT NULL, descripcion VARCHAR(255) NOT NULL, existencia DOUBLE PRECISION NOT NULL, importe DOUBLE PRECISION NOT NULL, activo TINYINT(1) NOT NULL, nro_subcuenta_inventario VARCHAR(255) DEFAULT NULL, nro_cuenta_acreedora VARCHAR(255) DEFAULT NULL, nro_subcuenta_acreedora VARCHAR(255) DEFAULT NULL, INDEX IDX_9D094AE0E2C70A62 (id_amlacen_id), INDEX IDX_9D094AE0E16A5625 (id_unidad_medida_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE mercancia_producto (id INT AUTO_INCREMENT NOT NULL, id_mercancia_id INT NOT NULL, id_producto_id INT NOT NULL, INDEX IDX_3F705CF59F287F54 (id_mercancia_id), INDEX IDX_3F705CF56E57A479 (id_producto_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE modulo (id INT NOT NULL, nombre VARCHAR(255) NOT NULL, activo TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE moneda (id INT AUTO_INCREMENT NOT NULL, nombre VARCHAR(255) NOT NULL, activo TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE movimiento (id INT AUTO_INCREMENT NOT NULL, id_tipo_documento_activo_fijo_id INT NOT NULL, id_tipo_movimiento_id INT NOT NULL, id_unidad_origen_id INT NOT NULL, id_unidad_destino_id INT NOT NULL, fecha DATE NOT NULL, activo TINYINT(1) NOT NULL, INDEX IDX_C8FF107AD1CE493D (id_tipo_documento_activo_fijo_id), INDEX IDX_C8FF107ADB763453 (id_tipo_movimiento_id), INDEX IDX_C8FF107A873C7FC7 (id_unidad_origen_id), INDEX IDX_C8FF107A4F781EA (id_unidad_destino_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE movimiento_activo_fijo (id INT AUTO_INCREMENT NOT NULL, id_unidad_id INT NOT NULL, id_activo_fijo_id INT NOT NULL, id_tipo_movimiento_id INT NOT NULL, id_cuenta_id INT NOT NULL, id_subcuenta_id INT NOT NULL, id_usuario_id INT NOT NULL, fecha DATE NOT NULL, fundamentacion VARCHAR(255) NOT NULL, entrada TINYINT(1) NOT NULL, nro_consecutivo INT NOT NULL, anno INT NOT NULL, activo TINYINT(1) NOT NULL, INDEX IDX_A985A0DA1D34FA6B (id_unidad_id), INDEX IDX_A985A0DA5832E72E (id_activo_fijo_id), INDEX IDX_A985A0DADB763453 (id_tipo_movimiento_id), INDEX IDX_A985A0DA1ADA4D3F (id_cuenta_id), INDEX IDX_A985A0DA2D412F53 (id_subcuenta_id), INDEX IDX_A985A0DA7EB2C349 (id_usuario_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE movimiento_mercancia (id INT AUTO_INCREMENT NOT NULL, id_mercancia_id INT NOT NULL, id_documento_id INT NOT NULL, id_tipo_documento_id INT NOT NULL, id_usuario_id INT DEFAULT NULL, id_centro_costo_id INT DEFAULT NULL, id_elemento_gasto_id INT DEFAULT NULL, id_almacen_id INT DEFAULT NULL, id_expediente_id INT DEFAULT NULL, id_orden_trabajo_id INT DEFAULT NULL, id_factura_id INT DEFAULT NULL, cantidad DOUBLE PRECISION NOT NULL, importe DOUBLE PRECISION NOT NULL, existencia DOUBLE PRECISION NOT NULL, fecha DATE NOT NULL, activo TINYINT(1) NOT NULL, entrada TINYINT(1) NOT NULL, cuenta VARCHAR(255) DEFAULT NULL, nro_subcuenta_deudora VARCHAR(255) DEFAULT NULL, INDEX IDX_44876BD79F287F54 (id_mercancia_id), INDEX IDX_44876BD76601BA07 (id_documento_id), INDEX IDX_44876BD77A4F962 (id_tipo_documento_id), INDEX IDX_44876BD77EB2C349 (id_usuario_id), INDEX IDX_44876BD7C59B01FF (id_centro_costo_id), INDEX IDX_44876BD7F66372E9 (id_elemento_gasto_id), INDEX IDX_44876BD739161EBF (id_almacen_id), INDEX IDX_44876BD7F5DBAF2B (id_expediente_id), INDEX IDX_44876BD771381BB3 (id_orden_trabajo_id), INDEX IDX_44876BD755C5F988 (id_factura_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE movimiento_producto (id INT AUTO_INCREMENT NOT NULL, id_producto_id INT NOT NULL, id_documento_id INT NOT NULL, id_tipo_documento_id INT NOT NULL, id_usuario_id INT DEFAULT NULL, id_centro_costo_id INT DEFAULT NULL, id_elemento_gasto_id INT DEFAULT NULL, id_almacen_id INT DEFAULT NULL, id_orden_trabajo_id INT DEFAULT NULL, id_expediente_id INT DEFAULT NULL, id_factura_id INT DEFAULT NULL, cantidad DOUBLE PRECISION NOT NULL, importe DOUBLE PRECISION NOT NULL, existencia DOUBLE PRECISION NOT NULL, fecha DATE NOT NULL, activo TINYINT(1) NOT NULL, entrada TINYINT(1) NOT NULL, cuenta VARCHAR(255) DEFAULT NULL, nro_subcuenta_deudora VARCHAR(255) DEFAULT NULL, INDEX IDX_FFC0EDFC6E57A479 (id_producto_id), INDEX IDX_FFC0EDFC6601BA07 (id_documento_id), INDEX IDX_FFC0EDFC7A4F962 (id_tipo_documento_id), INDEX IDX_FFC0EDFC7EB2C349 (id_usuario_id), INDEX IDX_FFC0EDFCC59B01FF (id_centro_costo_id), INDEX IDX_FFC0EDFCF66372E9 (id_elemento_gasto_id), INDEX IDX_FFC0EDFC39161EBF (id_almacen_id), INDEX IDX_FFC0EDFC71381BB3 (id_orden_trabajo_id), INDEX IDX_FFC0EDFCF5DBAF2B (id_expediente_id), INDEX IDX_FFC0EDFC55C5F988 (id_factura_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE movimiento_venta (id INT AUTO_INCREMENT NOT NULL, id_factura_id INT NOT NULL, id_almacen_id INT NOT NULL, id_centro_costo_acreedor_id INT DEFAULT NULL, id_orden_trabajo_acreedor_id INT DEFAULT NULL, id_elemento_gasto_acreedor_id INT DEFAULT NULL, id_expediente_acreedor_id INT DEFAULT NULL, mercancia TINYINT(1) NOT NULL, codigo VARCHAR(255) NOT NULL, cantidad DOUBLE PRECISION NOT NULL, precio DOUBLE PRECISION NOT NULL, descuento_recarga DOUBLE PRECISION DEFAULT NULL, existencia DOUBLE PRECISION DEFAULT NULL, activo TINYINT(1) NOT NULL, cuenta VARCHAR(255) NOT NULL, nro_subcuenta_deudora VARCHAR(255) NOT NULL, costo DOUBLE PRECISION DEFAULT NULL, anno INT DEFAULT NULL, cuenta_nominal_acreedora VARCHAR(255) DEFAULT NULL, subcuenta_nominal_acreedora VARCHAR(255) DEFAULT NULL, descripcion VARCHAR(255) DEFAULT NULL, id_mercancia INT DEFAULT NULL, INDEX IDX_8E3F7AE555C5F988 (id_factura_id), INDEX IDX_8E3F7AE539161EBF (id_almacen_id), INDEX IDX_8E3F7AE5D8F8B0AD (id_centro_costo_acreedor_id), INDEX IDX_8E3F7AE5FA3DF5CD (id_orden_trabajo_acreedor_id), INDEX IDX_8E3F7AE5F0821C98 (id_elemento_gasto_acreedor_id), INDEX IDX_8E3F7AE56EA527F2 (id_expediente_acreedor_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE municipios (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(255) NOT NULL, nombre VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE obligacion_cobro (id INT AUTO_INCREMENT NOT NULL, id_factura_id INT NOT NULL, id_cliente INT NOT NULL, tipo_cliente INT NOT NULL, fecha_factura DATE NOT NULL, importe_factura DOUBLE PRECISION NOT NULL, cuenta_obligacion VARCHAR(255) NOT NULL, subcuenta_obligacion VARCHAR(255) DEFAULT NULL, resto_pagar DOUBLE PRECISION NOT NULL, liquidada TINYINT(1) NOT NULL, activo TINYINT(1) NOT NULL, INDEX IDX_807C726D55C5F988 (id_factura_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE obligacion_pago (id INT AUTO_INCREMENT NOT NULL, id_proveedor_id INT NOT NULL, id_documento_id INT NOT NULL, id_unidad_id INT NOT NULL, nro_cuenta VARCHAR(255) NOT NULL, nro_subcuenta VARCHAR(255) NOT NULL, valor_pagado DOUBLE PRECISION DEFAULT NULL, resto DOUBLE PRECISION NOT NULL, liquidado TINYINT(1) NOT NULL, activo TINYINT(1) NOT NULL, codigo_factura VARCHAR(255) NOT NULL, fecha_factura DATE NOT NULL, INDEX IDX_403C9B3BE8F12801 (id_proveedor_id), INDEX IDX_403C9B3B6601BA07 (id_documento_id), INDEX IDX_403C9B3B1D34FA6B (id_unidad_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE orden_trabajo (id INT AUTO_INCREMENT NOT NULL, id_unidad_id INT DEFAULT NULL, id_almacen_id INT DEFAULT NULL, codigo VARCHAR(255) NOT NULL, descripcion VARCHAR(255) NOT NULL, activo TINYINT(1) NOT NULL, anno INT NOT NULL, INDEX IDX_4158A0241D34FA6B (id_unidad_id), INDEX IDX_4158A02439161EBF (id_almacen_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE producto (id INT AUTO_INCREMENT NOT NULL, id_amlacen_id INT NOT NULL, id_unidad_medida_id INT NOT NULL, codigo VARCHAR(255) NOT NULL, cuenta VARCHAR(255) NOT NULL, descripcion VARCHAR(255) NOT NULL, existencia DOUBLE PRECISION NOT NULL, importe DOUBLE PRECISION NOT NULL, activo TINYINT(1) NOT NULL, nro_subcuenta_inventario VARCHAR(255) DEFAULT NULL, nro_cuenta_acreedora VARCHAR(255) DEFAULT NULL, nro_subcuenta_acreedora VARCHAR(255) DEFAULT NULL, INDEX IDX_A7BB0615E2C70A62 (id_amlacen_id), INDEX IDX_A7BB0615E16A5625 (id_unidad_medida_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE proveedor (id INT AUTO_INCREMENT NOT NULL, nombre VARCHAR(255) NOT NULL, codigo VARCHAR(255) NOT NULL, activo TINYINT(1) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE provincias (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(255) NOT NULL, nombre VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE registro_comprobantes (id INT AUTO_INCREMENT NOT NULL, id_unidad_id INT NOT NULL, id_tipo_comprobante_id INT NOT NULL, id_usuario_id INT NOT NULL, id_almacen_id INT DEFAULT NULL, nro_consecutivo INT NOT NULL, fecha DATE NOT NULL, descripcion VARCHAR(255) NOT NULL, debito DOUBLE PRECISION NOT NULL, credito DOUBLE PRECISION NOT NULL, anno INT NOT NULL, tipo INT DEFAULT NULL, INDEX IDX_B2D1B2B21D34FA6B (id_unidad_id), INDEX IDX_B2D1B2B2EF5F7851 (id_tipo_comprobante_id), INDEX IDX_B2D1B2B27EB2C349 (id_usuario_id), INDEX IDX_B2D1B2B239161EBF (id_almacen_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE reset_password_request (id INT AUTO_INCREMENT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE saldo_cuentas (id INT AUTO_INCREMENT NOT NULL, id_cuenta_id INT NOT NULL, id_subcuenta_id INT NOT NULL, id_centro_costo_id INT DEFAULT NULL, id_elemento_gasto_id INT DEFAULT NULL, id_almacen_id INT DEFAULT NULL, id_unidad_id INT NOT NULL, id_proveedor_id INT DEFAULT NULL, id_expediente_id INT DEFAULT NULL, id_orden_trabajo_id INT DEFAULT NULL, mes INT NOT NULL, anno INT NOT NULL, saldo DOUBLE PRECISION NOT NULL, INDEX IDX_BB2B71AE1ADA4D3F (id_cuenta_id), INDEX IDX_BB2B71AE2D412F53 (id_subcuenta_id), INDEX IDX_BB2B71AEC59B01FF (id_centro_costo_id), INDEX IDX_BB2B71AEF66372E9 (id_elemento_gasto_id), INDEX IDX_BB2B71AE39161EBF (id_almacen_id), INDEX IDX_BB2B71AE1D34FA6B (id_unidad_id), INDEX IDX_BB2B71AEE8F12801 (id_proveedor_id), INDEX IDX_BB2B71AEF5DBAF2B (id_expediente_id), INDEX IDX_BB2B71AE71381BB3 (id_orden_trabajo_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE solicitud_turismo (id INT AUTO_INCREMENT NOT NULL, vuelo_cantidad_adultos VARCHAR(255) DEFAULT NULL, vuelo_cantidad_ninos VARCHAR(255) DEFAULT NULL, vuelo_origen VARCHAR(255) DEFAULT NULL, vuelo_destino VARCHAR(255) DEFAULT NULL, vuelo_ida VARCHAR(255) DEFAULT NULL, vuelo_vuelta VARCHAR(255) DEFAULT NULL, vuelo_comentario VARCHAR(255) DEFAULT NULL, hotel_destino VARCHAR(255) DEFAULT NULL, hotel_nombre VARCHAR(255) DEFAULT NULL, hotel_categoria VARCHAR(255) DEFAULT NULL, hotel_plan VARCHAR(255) DEFAULT NULL, hotel_comentario VARCHAR(255) DEFAULT NULL, tranfer_llegada VARCHAR(255) DEFAULT NULL, tramfer_salida VARCHAR(255) DEFAULT NULL, tramfer_lugar VARCHAR(255) DEFAULT NULL, tramfer_destino VARCHAR(255) DEFAULT NULL, tramfer_vehiculo VARCHAR(255) DEFAULT NULL, tramfer_comentario VARCHAR(255) DEFAULT NULL, tour_nombre VARCHAR(255) DEFAULT NULL, tour_fecha VARCHAR(255) DEFAULT NULL, tour_comentario VARCHAR(255) DEFAULT NULL, rent_tipo_vehiculo VARCHAR(255) DEFAULT NULL, rent_lugar_recogida VARCHAR(255) DEFAULT NULL, rent_lugar_entrega VARCHAR(255) DEFAULT NULL, rent_comentario VARCHAR(255) DEFAULT NULL, rent_fecha_desde VARCHAR(255) DEFAULT NULL, hotel_desde VARCHAR(255) DEFAULT NULL, hotel_hasta VARCHAR(255) DEFAULT NULL, rent_fecha_hasta VARCHAR(255) DEFAULT NULL, empleado VARCHAR(255) DEFAULT NULL, id_cliente VARCHAR(255) DEFAULT NULL, fecha_solicitud DATETIME DEFAULT NULL, stado VARCHAR(255) DEFAULT NULL, nombre_cliente VARCHAR(255) DEFAULT NULL, hotel_adultos VARCHAR(255) DEFAULT NULL, hotel_ninos VARCHAR(255) DEFAULT NULL, tramfer_adultos VARCHAR(255) DEFAULT NULL, tramfer_ninos VARCHAR(255) DEFAULT NULL, tramfer_ida_vuelta VARCHAR(255) DEFAULT NULL, tour_ninos VARCHAR(255) DEFAULT NULL, tour_adultos VARCHAR(255) DEFAULT NULL, rent_cantidad_personas VARCHAR(255) DEFAULT NULL, empleado_status VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE stripe_factura (id INT AUTO_INCREMENT NOT NULL, auth VARCHAR(255) NOT NULL, estatus VARCHAR(255) NOT NULL, cliente_id VARCHAR(255) NOT NULL, id_empleado VARCHAR(255) NOT NULL, monto VARCHAR(255) NOT NULL, fecha DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE subcuenta (id INT AUTO_INCREMENT NOT NULL, id_cuenta_id INT NOT NULL, nro_subcuenta VARCHAR(255) NOT NULL, elemento_gasto TINYINT(1) NOT NULL, descripcion VARCHAR(255) NOT NULL, deudora TINYINT(1) NOT NULL, activo TINYINT(1) NOT NULL, INDEX IDX_57BB37EA1ADA4D3F (id_cuenta_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE subcuenta_criterio_analisis (id INT AUTO_INCREMENT NOT NULL, id_subcuenta_id INT NOT NULL, id_criterio_analisis_id INT NOT NULL, INDEX IDX_52A4A7682D412F53 (id_subcuenta_id), INDEX IDX_52A4A7685ABBE5F6 (id_criterio_analisis_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE subcuenta_proveedor (id INT AUTO_INCREMENT NOT NULL, id_subcuenta_id INT NOT NULL, id_proveedor_id INT NOT NULL, INDEX IDX_5C22E4B82D412F53 (id_subcuenta_id), INDEX IDX_5C22E4B8E8F12801 (id_proveedor_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tasa_cambio (id INT AUTO_INCREMENT NOT NULL, id_moneda_origen_id INT NOT NULL, id_moneda_destino_id INT NOT NULL, anno INT NOT NULL, mes INT NOT NULL, valor DOUBLE PRECISION NOT NULL, activo TINYINT(1) NOT NULL, INDEX IDX_DAB48606FA5CADE9 (id_moneda_origen_id), INDEX IDX_DAB48606D85CECF7 (id_moneda_destino_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE test_crud (id INT AUTO_INCREMENT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tipo_comprobante (id INT NOT NULL, descripcion VARCHAR(255) NOT NULL, activo TINYINT(1) NOT NULL, abreviatura VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tipo_cuenta (id INT AUTO_INCREMENT NOT NULL, nombre VARCHAR(255) NOT NULL, activo TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tipo_documento (id INT NOT NULL, nombre VARCHAR(255) NOT NULL, activo TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tipo_documento_activo_fijo (id INT AUTO_INCREMENT NOT NULL, descripcion VARCHAR(255) NOT NULL, activo TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tipo_movimiento (id INT AUTO_INCREMENT NOT NULL, descripcion VARCHAR(255) NOT NULL, activo TINYINT(1) NOT NULL, codigo VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE transferencia (id INT AUTO_INCREMENT NOT NULL, id_documento_id INT NOT NULL, id_unidad_id INT DEFAULT NULL, id_almacen_id INT DEFAULT NULL, nro_cuenta_inventario VARCHAR(255) NOT NULL, nro_subcuenta_inventario VARCHAR(255) NOT NULL, nro_cuenta_acreedora VARCHAR(255) NOT NULL, nro_subcuenta_acreedora VARCHAR(255) NOT NULL, nro_concecutivo VARCHAR(255) NOT NULL, anno INT NOT NULL, activo TINYINT(1) NOT NULL, entrada TINYINT(1) NOT NULL, INDEX IDX_EDC227306601BA07 (id_documento_id), INDEX IDX_EDC227301D34FA6B (id_unidad_id), INDEX IDX_EDC2273039161EBF (id_almacen_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE unidad (id INT AUTO_INCREMENT NOT NULL, id_padre_id INT DEFAULT NULL, nombre VARCHAR(255) NOT NULL, activo TINYINT(1) NOT NULL, codigo VARCHAR(255) DEFAULT NULL, direccion VARCHAR(255) DEFAULT NULL, telefono VARCHAR(255) DEFAULT NULL, correo VARCHAR(255) DEFAULT NULL, UNIQUE INDEX UNIQ_F3E6D02F3A909126 (nombre), UNIQUE INDEX UNIQ_F3E6D02F20332D99 (codigo), INDEX IDX_F3E6D02F31E700CD (id_padre_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE unidad_medida (id INT NOT NULL, nombre VARCHAR(255) NOT NULL, abreviatura VARCHAR(255) NOT NULL, activo TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user (id INT AUTO_INCREMENT NOT NULL, username VARCHAR(180) NOT NULL, roles JSON NOT NULL, status TINYINT(1) NOT NULL, password VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_8D93D649F85E0677 (username), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE vale_salida (id INT AUTO_INCREMENT NOT NULL, id_documento_id INT NOT NULL, activo TINYINT(1) NOT NULL, producto TINYINT(1) NOT NULL, nro_consecutivo VARCHAR(255) NOT NULL, anno INT NOT NULL, fecha_solicitud DATE NOT NULL, nro_solicitud VARCHAR(255) NOT NULL, nro_cuenta_deudora VARCHAR(255) NOT NULL, nro_subcuenta_deudora VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_90C265C86601BA07 (id_documento_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE activo_fijo ADD CONSTRAINT FK_75EBC93EDB763453 FOREIGN KEY (id_tipo_movimiento_id) REFERENCES tipo_movimiento (id)');
        $this->addSql('ALTER TABLE activo_fijo ADD CONSTRAINT FK_75EBC93E6FBA0327 FOREIGN KEY (id_tipo_movimiento_baja_id) REFERENCES tipo_movimiento (id)');
        $this->addSql('ALTER TABLE activo_fijo ADD CONSTRAINT FK_75EBC93ED410562 FOREIGN KEY (id_area_responsabilidad_id) REFERENCES area_responsabilidad (id)');
        $this->addSql('ALTER TABLE activo_fijo ADD CONSTRAINT FK_75EBC93E4A667A2B FOREIGN KEY (id_grupo_activo_id) REFERENCES grupo_activos (id)');
        $this->addSql('ALTER TABLE activo_fijo ADD CONSTRAINT FK_75EBC93E1D34FA6B FOREIGN KEY (id_unidad_id) REFERENCES unidad (id)');
        $this->addSql('ALTER TABLE activo_fijo_cuentas ADD CONSTRAINT FK_E0DF2901C84BDE84 FOREIGN KEY (id_activo_id) REFERENCES activo_fijo (id)');
        $this->addSql('ALTER TABLE activo_fijo_cuentas ADD CONSTRAINT FK_E0DF290186762CC7 FOREIGN KEY (id_cuenta_activo_id) REFERENCES cuenta (id)');
        $this->addSql('ALTER TABLE activo_fijo_cuentas ADD CONSTRAINT FK_E0DF29014476721E FOREIGN KEY (id_subcuenta_activo_id) REFERENCES subcuenta (id)');
        $this->addSql('ALTER TABLE activo_fijo_cuentas ADD CONSTRAINT FK_E0DF29012955A16D FOREIGN KEY (id_centro_costo_activo_id) REFERENCES centro_costo (id)');
        $this->addSql('ALTER TABLE activo_fijo_cuentas ADD CONSTRAINT FK_E0DF29014C675596 FOREIGN KEY (id_area_responsabilidad_activo_id) REFERENCES area_responsabilidad (id)');
        $this->addSql('ALTER TABLE activo_fijo_cuentas ADD CONSTRAINT FK_E0DF290174A5FFBA FOREIGN KEY (id_cuenta_depreciacion_id) REFERENCES cuenta (id)');
        $this->addSql('ALTER TABLE activo_fijo_cuentas ADD CONSTRAINT FK_E0DF2901549C81D9 FOREIGN KEY (id_subcuenta_depreciacion_id) REFERENCES subcuenta (id)');
        $this->addSql('ALTER TABLE activo_fijo_cuentas ADD CONSTRAINT FK_E0DF290180C608FA FOREIGN KEY (id_cuenta_gasto_id) REFERENCES cuenta (id)');
        $this->addSql('ALTER TABLE activo_fijo_cuentas ADD CONSTRAINT FK_E0DF290157677646 FOREIGN KEY (id_subcuenta_gasto_id) REFERENCES subcuenta (id)');
        $this->addSql('ALTER TABLE activo_fijo_cuentas ADD CONSTRAINT FK_E0DF2901A950EE53 FOREIGN KEY (id_centro_costo_gasto_id) REFERENCES centro_costo (id)');
        $this->addSql('ALTER TABLE activo_fijo_cuentas ADD CONSTRAINT FK_E0DF2901A752F04B FOREIGN KEY (id_elemento_gasto_gasto_id) REFERENCES elemento_gasto (id)');
        $this->addSql('ALTER TABLE activo_fijo_movimiento_activo_fijo ADD CONSTRAINT FK_2FA61FF25832E72E FOREIGN KEY (id_activo_fijo_id) REFERENCES activo_fijo (id)');
        $this->addSql('ALTER TABLE activo_fijo_movimiento_activo_fijo ADD CONSTRAINT FK_2FA61FF27786CA71 FOREIGN KEY (id_movimiento_activo_fijo_id) REFERENCES movimiento (id)');
        $this->addSql('ALTER TABLE ajuste ADD CONSTRAINT FK_DD35BD326601BA07 FOREIGN KEY (id_documento_id) REFERENCES documento (id)');
        $this->addSql('ALTER TABLE almacen ADD CONSTRAINT FK_D5B2D2501D34FA6B FOREIGN KEY (id_unidad_id) REFERENCES unidad (id)');
        $this->addSql('ALTER TABLE almacen_ocupado ADD CONSTRAINT FK_AA53605839161EBF FOREIGN KEY (id_almacen_id) REFERENCES almacen (id)');
        $this->addSql('ALTER TABLE almacen_ocupado ADD CONSTRAINT FK_AA5360587EB2C349 FOREIGN KEY (id_usuario_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE area_responsabilidad ADD CONSTRAINT FK_F469C2BA1D34FA6B FOREIGN KEY (id_unidad_id) REFERENCES unidad (id)');
        $this->addSql('ALTER TABLE centro_costo ADD CONSTRAINT FK_749608CE1D34FA6B FOREIGN KEY (id_unidad_id) REFERENCES unidad (id)');
        $this->addSql('ALTER TABLE cierre ADD CONSTRAINT FK_D0DCFCC739161EBF FOREIGN KEY (id_almacen_id) REFERENCES almacen (id)');
        $this->addSql('ALTER TABLE cierre ADD CONSTRAINT FK_D0DCFCC77EB2C349 FOREIGN KEY (id_usuario_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE cierre_diario ADD CONSTRAINT FK_F3D0CD8939161EBF FOREIGN KEY (id_almacen_id) REFERENCES almacen (id)');
        $this->addSql('ALTER TABLE cierre_diario ADD CONSTRAINT FK_F3D0CD897EB2C349 FOREIGN KEY (id_usuario_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE comprobante_cierre ADD CONSTRAINT FK_D03EA4C51800963C FOREIGN KEY (id_comprobante_id) REFERENCES registro_comprobantes (id)');
        $this->addSql('ALTER TABLE comprobante_cierre ADD CONSTRAINT FK_D03EA4C545F8C94C FOREIGN KEY (id_cierre_id) REFERENCES cierre (id)');
        $this->addSql('ALTER TABLE configuracion_inicial ADD CONSTRAINT FK_8521BE24404AE9D2 FOREIGN KEY (id_modulo_id) REFERENCES modulo (id)');
        $this->addSql('ALTER TABLE configuracion_inicial ADD CONSTRAINT FK_8521BE247A4F962 FOREIGN KEY (id_tipo_documento_id) REFERENCES tipo_documento (id)');
        $this->addSql('ALTER TABLE contratos_cliente ADD CONSTRAINT FK_29A5BB477BF9CE86 FOREIGN KEY (id_cliente_id) REFERENCES cliente_contabilidad (id)');
        $this->addSql('ALTER TABLE contratos_cliente ADD CONSTRAINT FK_29A5BB47374388F5 FOREIGN KEY (id_moneda_id) REFERENCES moneda (id)');
        $this->addSql('ALTER TABLE cuadre_diario ADD CONSTRAINT FK_60ABEFD91ADA4D3F FOREIGN KEY (id_cuenta_id) REFERENCES cuenta (id)');
        $this->addSql('ALTER TABLE cuadre_diario ADD CONSTRAINT FK_60ABEFD92D412F53 FOREIGN KEY (id_subcuenta_id) REFERENCES subcuenta (id)');
        $this->addSql('ALTER TABLE cuadre_diario ADD CONSTRAINT FK_60ABEFD945F8C94C FOREIGN KEY (id_cierre_id) REFERENCES cierre (id)');
        $this->addSql('ALTER TABLE cuadre_diario ADD CONSTRAINT FK_60ABEFD939161EBF FOREIGN KEY (id_almacen_id) REFERENCES almacen (id)');
        $this->addSql('ALTER TABLE cuenta ADD CONSTRAINT FK_31C7BFCF45E7F350 FOREIGN KEY (id_tipo_cuenta_id) REFERENCES tipo_cuenta (id)');
        $this->addSql('ALTER TABLE cuenta_criterio_analisis ADD CONSTRAINT FK_AF040B091ADA4D3F FOREIGN KEY (id_cuenta_id) REFERENCES cuenta (id)');
        $this->addSql('ALTER TABLE cuenta_criterio_analisis ADD CONSTRAINT FK_AF040B095ABBE5F6 FOREIGN KEY (id_criterio_analisis_id) REFERENCES criterio_analisis (id)');
        $this->addSql('ALTER TABLE cuentas_cliente ADD CONSTRAINT FK_64653310374388F5 FOREIGN KEY (id_moneda_id) REFERENCES moneda (id)');
        $this->addSql('ALTER TABLE cuentas_cliente ADD CONSTRAINT FK_646533107BF9CE86 FOREIGN KEY (id_cliente_id) REFERENCES cliente_contabilidad (id)');
        $this->addSql('ALTER TABLE custom_user ADD CONSTRAINT FK_8CE51EB479F37AE5 FOREIGN KEY (id_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE depreciacion ADD CONSTRAINT FK_D618AE145832E72E FOREIGN KEY (id_activo_fijo_id) REFERENCES activo_fijo (id)');
        $this->addSql('ALTER TABLE devolucion ADD CONSTRAINT FK_524D9F676601BA07 FOREIGN KEY (id_documento_id) REFERENCES documento (id)');
        $this->addSql('ALTER TABLE devolucion ADD CONSTRAINT FK_524D9F671D34FA6B FOREIGN KEY (id_unidad_id) REFERENCES unidad (id)');
        $this->addSql('ALTER TABLE devolucion ADD CONSTRAINT FK_524D9F6739161EBF FOREIGN KEY (id_almacen_id) REFERENCES almacen (id)');
        $this->addSql('ALTER TABLE devolucion ADD CONSTRAINT FK_524D9F67C59B01FF FOREIGN KEY (id_centro_costo_id) REFERENCES centro_costo (id)');
        $this->addSql('ALTER TABLE devolucion ADD CONSTRAINT FK_524D9F67F66372E9 FOREIGN KEY (id_elemento_gasto_id) REFERENCES elemento_gasto (id)');
        $this->addSql('ALTER TABLE devolucion ADD CONSTRAINT FK_524D9F675074DD86 FOREIGN KEY (id_orden_tabajo_id) REFERENCES orden_trabajo (id)');
        $this->addSql('ALTER TABLE documento ADD CONSTRAINT FK_B6B12EC739161EBF FOREIGN KEY (id_almacen_id) REFERENCES almacen (id)');
        $this->addSql('ALTER TABLE documento ADD CONSTRAINT FK_B6B12EC71D34FA6B FOREIGN KEY (id_unidad_id) REFERENCES unidad (id)');
        $this->addSql('ALTER TABLE documento ADD CONSTRAINT FK_B6B12EC7374388F5 FOREIGN KEY (id_moneda_id) REFERENCES moneda (id)');
        $this->addSql('ALTER TABLE documento ADD CONSTRAINT FK_B6B12EC77A4F962 FOREIGN KEY (id_tipo_documento_id) REFERENCES tipo_documento (id)');
        $this->addSql('ALTER TABLE empleado ADD CONSTRAINT FK_D9D9BF521D34FA6B FOREIGN KEY (id_unidad_id) REFERENCES unidad (id)');
        $this->addSql('ALTER TABLE empleado ADD CONSTRAINT FK_D9D9BF52D1E12F15 FOREIGN KEY (id_cargo_id) REFERENCES cargo (id)');
        $this->addSql('ALTER TABLE empleado ADD CONSTRAINT FK_D9D9BF527EB2C349 FOREIGN KEY (id_usuario_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE expediente ADD CONSTRAINT FK_D59CA4131D34FA6B FOREIGN KEY (id_unidad_id) REFERENCES unidad (id)');
        $this->addSql('ALTER TABLE factura ADD CONSTRAINT FK_F9EBA00968BCB606 FOREIGN KEY (id_contrato_id) REFERENCES contratos_cliente (id)');
        $this->addSql('ALTER TABLE factura ADD CONSTRAINT FK_F9EBA0091D34FA6B FOREIGN KEY (id_unidad_id) REFERENCES unidad (id)');
        $this->addSql('ALTER TABLE factura ADD CONSTRAINT FK_F9EBA0097EB2C349 FOREIGN KEY (id_usuario_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE factura ADD CONSTRAINT FK_F9EBA009C59B01FF FOREIGN KEY (id_centro_costo_id) REFERENCES centro_costo (id)');
        $this->addSql('ALTER TABLE factura ADD CONSTRAINT FK_F9EBA00971381BB3 FOREIGN KEY (id_orden_trabajo_id) REFERENCES orden_trabajo (id)');
        $this->addSql('ALTER TABLE factura ADD CONSTRAINT FK_F9EBA009F66372E9 FOREIGN KEY (id_elemento_gasto_id) REFERENCES elemento_gasto (id)');
        $this->addSql('ALTER TABLE factura ADD CONSTRAINT FK_F9EBA009F5DBAF2B FOREIGN KEY (id_expediente_id) REFERENCES expediente (id)');
        $this->addSql('ALTER TABLE factura_documento ADD CONSTRAINT FK_CCC060C155C5F988 FOREIGN KEY (id_factura_id) REFERENCES factura (id)');
        $this->addSql('ALTER TABLE factura_documento ADD CONSTRAINT FK_CCC060C16601BA07 FOREIGN KEY (id_documento_id) REFERENCES documento (id)');
        $this->addSql('ALTER TABLE factura_documento ADD CONSTRAINT FK_CCC060C1EC34F77F FOREIGN KEY (id_movimiento_venta_id) REFERENCES movimiento_venta (id)');
        $this->addSql('ALTER TABLE facturas_comprobante ADD CONSTRAINT FK_6FD2F19B55C5F988 FOREIGN KEY (id_factura_id) REFERENCES factura (id)');
        $this->addSql('ALTER TABLE facturas_comprobante ADD CONSTRAINT FK_6FD2F19B1800963C FOREIGN KEY (id_comprobante_id) REFERENCES registro_comprobantes (id)');
        $this->addSql('ALTER TABLE facturas_comprobante ADD CONSTRAINT FK_6FD2F19B1D34FA6B FOREIGN KEY (id_unidad_id) REFERENCES unidad (id)');
        $this->addSql('ALTER TABLE informe_recepcion ADD CONSTRAINT FK_62A4EBD6601BA07 FOREIGN KEY (id_documento_id) REFERENCES documento (id)');
        $this->addSql('ALTER TABLE informe_recepcion ADD CONSTRAINT FK_62A4EBDE8F12801 FOREIGN KEY (id_proveedor_id) REFERENCES proveedor (id)');
        $this->addSql('ALTER TABLE mercancia ADD CONSTRAINT FK_9D094AE0E2C70A62 FOREIGN KEY (id_amlacen_id) REFERENCES almacen (id)');
        $this->addSql('ALTER TABLE mercancia ADD CONSTRAINT FK_9D094AE0E16A5625 FOREIGN KEY (id_unidad_medida_id) REFERENCES unidad_medida (id)');
        $this->addSql('ALTER TABLE mercancia_producto ADD CONSTRAINT FK_3F705CF59F287F54 FOREIGN KEY (id_mercancia_id) REFERENCES mercancia (id)');
        $this->addSql('ALTER TABLE mercancia_producto ADD CONSTRAINT FK_3F705CF56E57A479 FOREIGN KEY (id_producto_id) REFERENCES producto (id)');
        $this->addSql('ALTER TABLE movimiento ADD CONSTRAINT FK_C8FF107AD1CE493D FOREIGN KEY (id_tipo_documento_activo_fijo_id) REFERENCES tipo_documento_activo_fijo (id)');
        $this->addSql('ALTER TABLE movimiento ADD CONSTRAINT FK_C8FF107ADB763453 FOREIGN KEY (id_tipo_movimiento_id) REFERENCES tipo_movimiento (id)');
        $this->addSql('ALTER TABLE movimiento ADD CONSTRAINT FK_C8FF107A873C7FC7 FOREIGN KEY (id_unidad_origen_id) REFERENCES unidad (id)');
        $this->addSql('ALTER TABLE movimiento ADD CONSTRAINT FK_C8FF107A4F781EA FOREIGN KEY (id_unidad_destino_id) REFERENCES unidad (id)');
        $this->addSql('ALTER TABLE movimiento_activo_fijo ADD CONSTRAINT FK_A985A0DA1D34FA6B FOREIGN KEY (id_unidad_id) REFERENCES unidad (id)');
        $this->addSql('ALTER TABLE movimiento_activo_fijo ADD CONSTRAINT FK_A985A0DA5832E72E FOREIGN KEY (id_activo_fijo_id) REFERENCES activo_fijo (id)');
        $this->addSql('ALTER TABLE movimiento_activo_fijo ADD CONSTRAINT FK_A985A0DADB763453 FOREIGN KEY (id_tipo_movimiento_id) REFERENCES tipo_movimiento (id)');
        $this->addSql('ALTER TABLE movimiento_activo_fijo ADD CONSTRAINT FK_A985A0DA1ADA4D3F FOREIGN KEY (id_cuenta_id) REFERENCES cuenta (id)');
        $this->addSql('ALTER TABLE movimiento_activo_fijo ADD CONSTRAINT FK_A985A0DA2D412F53 FOREIGN KEY (id_subcuenta_id) REFERENCES subcuenta (id)');
        $this->addSql('ALTER TABLE movimiento_activo_fijo ADD CONSTRAINT FK_A985A0DA7EB2C349 FOREIGN KEY (id_usuario_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE movimiento_mercancia ADD CONSTRAINT FK_44876BD79F287F54 FOREIGN KEY (id_mercancia_id) REFERENCES mercancia (id)');
        $this->addSql('ALTER TABLE movimiento_mercancia ADD CONSTRAINT FK_44876BD76601BA07 FOREIGN KEY (id_documento_id) REFERENCES documento (id)');
        $this->addSql('ALTER TABLE movimiento_mercancia ADD CONSTRAINT FK_44876BD77A4F962 FOREIGN KEY (id_tipo_documento_id) REFERENCES tipo_documento (id)');
        $this->addSql('ALTER TABLE movimiento_mercancia ADD CONSTRAINT FK_44876BD77EB2C349 FOREIGN KEY (id_usuario_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE movimiento_mercancia ADD CONSTRAINT FK_44876BD7C59B01FF FOREIGN KEY (id_centro_costo_id) REFERENCES centro_costo (id)');
        $this->addSql('ALTER TABLE movimiento_mercancia ADD CONSTRAINT FK_44876BD7F66372E9 FOREIGN KEY (id_elemento_gasto_id) REFERENCES elemento_gasto (id)');
        $this->addSql('ALTER TABLE movimiento_mercancia ADD CONSTRAINT FK_44876BD739161EBF FOREIGN KEY (id_almacen_id) REFERENCES almacen (id)');
        $this->addSql('ALTER TABLE movimiento_mercancia ADD CONSTRAINT FK_44876BD7F5DBAF2B FOREIGN KEY (id_expediente_id) REFERENCES expediente (id)');
        $this->addSql('ALTER TABLE movimiento_mercancia ADD CONSTRAINT FK_44876BD771381BB3 FOREIGN KEY (id_orden_trabajo_id) REFERENCES orden_trabajo (id)');
        $this->addSql('ALTER TABLE movimiento_mercancia ADD CONSTRAINT FK_44876BD755C5F988 FOREIGN KEY (id_factura_id) REFERENCES factura (id)');
        $this->addSql('ALTER TABLE movimiento_producto ADD CONSTRAINT FK_FFC0EDFC6E57A479 FOREIGN KEY (id_producto_id) REFERENCES producto (id)');
        $this->addSql('ALTER TABLE movimiento_producto ADD CONSTRAINT FK_FFC0EDFC6601BA07 FOREIGN KEY (id_documento_id) REFERENCES documento (id)');
        $this->addSql('ALTER TABLE movimiento_producto ADD CONSTRAINT FK_FFC0EDFC7A4F962 FOREIGN KEY (id_tipo_documento_id) REFERENCES tipo_documento (id)');
        $this->addSql('ALTER TABLE movimiento_producto ADD CONSTRAINT FK_FFC0EDFC7EB2C349 FOREIGN KEY (id_usuario_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE movimiento_producto ADD CONSTRAINT FK_FFC0EDFCC59B01FF FOREIGN KEY (id_centro_costo_id) REFERENCES centro_costo (id)');
        $this->addSql('ALTER TABLE movimiento_producto ADD CONSTRAINT FK_FFC0EDFCF66372E9 FOREIGN KEY (id_elemento_gasto_id) REFERENCES elemento_gasto (id)');
        $this->addSql('ALTER TABLE movimiento_producto ADD CONSTRAINT FK_FFC0EDFC39161EBF FOREIGN KEY (id_almacen_id) REFERENCES almacen (id)');
        $this->addSql('ALTER TABLE movimiento_producto ADD CONSTRAINT FK_FFC0EDFC71381BB3 FOREIGN KEY (id_orden_trabajo_id) REFERENCES orden_trabajo (id)');
        $this->addSql('ALTER TABLE movimiento_producto ADD CONSTRAINT FK_FFC0EDFCF5DBAF2B FOREIGN KEY (id_expediente_id) REFERENCES expediente (id)');
        $this->addSql('ALTER TABLE movimiento_producto ADD CONSTRAINT FK_FFC0EDFC55C5F988 FOREIGN KEY (id_factura_id) REFERENCES factura (id)');
        $this->addSql('ALTER TABLE movimiento_venta ADD CONSTRAINT FK_8E3F7AE555C5F988 FOREIGN KEY (id_factura_id) REFERENCES factura (id)');
        $this->addSql('ALTER TABLE movimiento_venta ADD CONSTRAINT FK_8E3F7AE539161EBF FOREIGN KEY (id_almacen_id) REFERENCES almacen (id)');
        $this->addSql('ALTER TABLE movimiento_venta ADD CONSTRAINT FK_8E3F7AE5D8F8B0AD FOREIGN KEY (id_centro_costo_acreedor_id) REFERENCES centro_costo (id)');
        $this->addSql('ALTER TABLE movimiento_venta ADD CONSTRAINT FK_8E3F7AE5FA3DF5CD FOREIGN KEY (id_orden_trabajo_acreedor_id) REFERENCES orden_trabajo (id)');
        $this->addSql('ALTER TABLE movimiento_venta ADD CONSTRAINT FK_8E3F7AE5F0821C98 FOREIGN KEY (id_elemento_gasto_acreedor_id) REFERENCES elemento_gasto (id)');
        $this->addSql('ALTER TABLE movimiento_venta ADD CONSTRAINT FK_8E3F7AE56EA527F2 FOREIGN KEY (id_expediente_acreedor_id) REFERENCES expediente (id)');
        $this->addSql('ALTER TABLE obligacion_cobro ADD CONSTRAINT FK_807C726D55C5F988 FOREIGN KEY (id_factura_id) REFERENCES factura (id)');
        $this->addSql('ALTER TABLE obligacion_pago ADD CONSTRAINT FK_403C9B3BE8F12801 FOREIGN KEY (id_proveedor_id) REFERENCES proveedor (id)');
        $this->addSql('ALTER TABLE obligacion_pago ADD CONSTRAINT FK_403C9B3B6601BA07 FOREIGN KEY (id_documento_id) REFERENCES documento (id)');
        $this->addSql('ALTER TABLE obligacion_pago ADD CONSTRAINT FK_403C9B3B1D34FA6B FOREIGN KEY (id_unidad_id) REFERENCES unidad (id)');
        $this->addSql('ALTER TABLE orden_trabajo ADD CONSTRAINT FK_4158A0241D34FA6B FOREIGN KEY (id_unidad_id) REFERENCES unidad (id)');
        $this->addSql('ALTER TABLE orden_trabajo ADD CONSTRAINT FK_4158A02439161EBF FOREIGN KEY (id_almacen_id) REFERENCES almacen (id)');
        $this->addSql('ALTER TABLE producto ADD CONSTRAINT FK_A7BB0615E2C70A62 FOREIGN KEY (id_amlacen_id) REFERENCES almacen (id)');
        $this->addSql('ALTER TABLE producto ADD CONSTRAINT FK_A7BB0615E16A5625 FOREIGN KEY (id_unidad_medida_id) REFERENCES unidad_medida (id)');
        $this->addSql('ALTER TABLE registro_comprobantes ADD CONSTRAINT FK_B2D1B2B21D34FA6B FOREIGN KEY (id_unidad_id) REFERENCES unidad (id)');
        $this->addSql('ALTER TABLE registro_comprobantes ADD CONSTRAINT FK_B2D1B2B2EF5F7851 FOREIGN KEY (id_tipo_comprobante_id) REFERENCES tipo_comprobante (id)');
        $this->addSql('ALTER TABLE registro_comprobantes ADD CONSTRAINT FK_B2D1B2B27EB2C349 FOREIGN KEY (id_usuario_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE registro_comprobantes ADD CONSTRAINT FK_B2D1B2B239161EBF FOREIGN KEY (id_almacen_id) REFERENCES almacen (id)');
        $this->addSql('ALTER TABLE saldo_cuentas ADD CONSTRAINT FK_BB2B71AE1ADA4D3F FOREIGN KEY (id_cuenta_id) REFERENCES cuenta (id)');
        $this->addSql('ALTER TABLE saldo_cuentas ADD CONSTRAINT FK_BB2B71AE2D412F53 FOREIGN KEY (id_subcuenta_id) REFERENCES subcuenta (id)');
        $this->addSql('ALTER TABLE saldo_cuentas ADD CONSTRAINT FK_BB2B71AEC59B01FF FOREIGN KEY (id_centro_costo_id) REFERENCES centro_costo (id)');
        $this->addSql('ALTER TABLE saldo_cuentas ADD CONSTRAINT FK_BB2B71AEF66372E9 FOREIGN KEY (id_elemento_gasto_id) REFERENCES elemento_gasto (id)');
        $this->addSql('ALTER TABLE saldo_cuentas ADD CONSTRAINT FK_BB2B71AE39161EBF FOREIGN KEY (id_almacen_id) REFERENCES almacen (id)');
        $this->addSql('ALTER TABLE saldo_cuentas ADD CONSTRAINT FK_BB2B71AE1D34FA6B FOREIGN KEY (id_unidad_id) REFERENCES unidad (id)');
        $this->addSql('ALTER TABLE saldo_cuentas ADD CONSTRAINT FK_BB2B71AEE8F12801 FOREIGN KEY (id_proveedor_id) REFERENCES proveedor (id)');
        $this->addSql('ALTER TABLE saldo_cuentas ADD CONSTRAINT FK_BB2B71AEF5DBAF2B FOREIGN KEY (id_expediente_id) REFERENCES expediente (id)');
        $this->addSql('ALTER TABLE saldo_cuentas ADD CONSTRAINT FK_BB2B71AE71381BB3 FOREIGN KEY (id_orden_trabajo_id) REFERENCES orden_trabajo (id)');
        $this->addSql('ALTER TABLE subcuenta ADD CONSTRAINT FK_57BB37EA1ADA4D3F FOREIGN KEY (id_cuenta_id) REFERENCES cuenta (id)');
        $this->addSql('ALTER TABLE subcuenta_criterio_analisis ADD CONSTRAINT FK_52A4A7682D412F53 FOREIGN KEY (id_subcuenta_id) REFERENCES subcuenta (id)');
        $this->addSql('ALTER TABLE subcuenta_criterio_analisis ADD CONSTRAINT FK_52A4A7685ABBE5F6 FOREIGN KEY (id_criterio_analisis_id) REFERENCES criterio_analisis (id)');
        $this->addSql('ALTER TABLE subcuenta_proveedor ADD CONSTRAINT FK_5C22E4B82D412F53 FOREIGN KEY (id_subcuenta_id) REFERENCES subcuenta (id)');
        $this->addSql('ALTER TABLE subcuenta_proveedor ADD CONSTRAINT FK_5C22E4B8E8F12801 FOREIGN KEY (id_proveedor_id) REFERENCES proveedor (id)');
        $this->addSql('ALTER TABLE tasa_cambio ADD CONSTRAINT FK_DAB48606FA5CADE9 FOREIGN KEY (id_moneda_origen_id) REFERENCES moneda (id)');
        $this->addSql('ALTER TABLE tasa_cambio ADD CONSTRAINT FK_DAB48606D85CECF7 FOREIGN KEY (id_moneda_destino_id) REFERENCES moneda (id)');
        $this->addSql('ALTER TABLE transferencia ADD CONSTRAINT FK_EDC227306601BA07 FOREIGN KEY (id_documento_id) REFERENCES documento (id)');
        $this->addSql('ALTER TABLE transferencia ADD CONSTRAINT FK_EDC227301D34FA6B FOREIGN KEY (id_unidad_id) REFERENCES unidad (id)');
        $this->addSql('ALTER TABLE transferencia ADD CONSTRAINT FK_EDC2273039161EBF FOREIGN KEY (id_almacen_id) REFERENCES almacen (id)');
        $this->addSql('ALTER TABLE unidad ADD CONSTRAINT FK_F3E6D02F31E700CD FOREIGN KEY (id_padre_id) REFERENCES unidad (id)');
        $this->addSql('ALTER TABLE vale_salida ADD CONSTRAINT FK_90C265C86601BA07 FOREIGN KEY (id_documento_id) REFERENCES documento (id)');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE activo_fijo_cuentas DROP FOREIGN KEY FK_E0DF2901C84BDE84');
        $this->addSql('ALTER TABLE activo_fijo_movimiento_activo_fijo DROP FOREIGN KEY FK_2FA61FF25832E72E');
        $this->addSql('ALTER TABLE depreciacion DROP FOREIGN KEY FK_D618AE145832E72E');
        $this->addSql('ALTER TABLE movimiento_activo_fijo DROP FOREIGN KEY FK_A985A0DA5832E72E');
        $this->addSql('ALTER TABLE almacen_ocupado DROP FOREIGN KEY FK_AA53605839161EBF');
        $this->addSql('ALTER TABLE cierre DROP FOREIGN KEY FK_D0DCFCC739161EBF');
        $this->addSql('ALTER TABLE cierre_diario DROP FOREIGN KEY FK_F3D0CD8939161EBF');
        $this->addSql('ALTER TABLE cuadre_diario DROP FOREIGN KEY FK_60ABEFD939161EBF');
        $this->addSql('ALTER TABLE devolucion DROP FOREIGN KEY FK_524D9F6739161EBF');
        $this->addSql('ALTER TABLE documento DROP FOREIGN KEY FK_B6B12EC739161EBF');
        $this->addSql('ALTER TABLE mercancia DROP FOREIGN KEY FK_9D094AE0E2C70A62');
        $this->addSql('ALTER TABLE movimiento_mercancia DROP FOREIGN KEY FK_44876BD739161EBF');
        $this->addSql('ALTER TABLE movimiento_producto DROP FOREIGN KEY FK_FFC0EDFC39161EBF');
        $this->addSql('ALTER TABLE movimiento_venta DROP FOREIGN KEY FK_8E3F7AE539161EBF');
        $this->addSql('ALTER TABLE orden_trabajo DROP FOREIGN KEY FK_4158A02439161EBF');
        $this->addSql('ALTER TABLE producto DROP FOREIGN KEY FK_A7BB0615E2C70A62');
        $this->addSql('ALTER TABLE registro_comprobantes DROP FOREIGN KEY FK_B2D1B2B239161EBF');
        $this->addSql('ALTER TABLE saldo_cuentas DROP FOREIGN KEY FK_BB2B71AE39161EBF');
        $this->addSql('ALTER TABLE transferencia DROP FOREIGN KEY FK_EDC2273039161EBF');
        $this->addSql('ALTER TABLE activo_fijo DROP FOREIGN KEY FK_75EBC93ED410562');
        $this->addSql('ALTER TABLE activo_fijo_cuentas DROP FOREIGN KEY FK_E0DF29014C675596');
        $this->addSql('ALTER TABLE empleado DROP FOREIGN KEY FK_D9D9BF52D1E12F15');
        $this->addSql('ALTER TABLE activo_fijo_cuentas DROP FOREIGN KEY FK_E0DF29012955A16D');
        $this->addSql('ALTER TABLE activo_fijo_cuentas DROP FOREIGN KEY FK_E0DF2901A950EE53');
        $this->addSql('ALTER TABLE devolucion DROP FOREIGN KEY FK_524D9F67C59B01FF');
        $this->addSql('ALTER TABLE factura DROP FOREIGN KEY FK_F9EBA009C59B01FF');
        $this->addSql('ALTER TABLE movimiento_mercancia DROP FOREIGN KEY FK_44876BD7C59B01FF');
        $this->addSql('ALTER TABLE movimiento_producto DROP FOREIGN KEY FK_FFC0EDFCC59B01FF');
        $this->addSql('ALTER TABLE movimiento_venta DROP FOREIGN KEY FK_8E3F7AE5D8F8B0AD');
        $this->addSql('ALTER TABLE saldo_cuentas DROP FOREIGN KEY FK_BB2B71AEC59B01FF');
        $this->addSql('ALTER TABLE comprobante_cierre DROP FOREIGN KEY FK_D03EA4C545F8C94C');
        $this->addSql('ALTER TABLE cuadre_diario DROP FOREIGN KEY FK_60ABEFD945F8C94C');
        $this->addSql('ALTER TABLE contratos_cliente DROP FOREIGN KEY FK_29A5BB477BF9CE86');
        $this->addSql('ALTER TABLE cuentas_cliente DROP FOREIGN KEY FK_646533107BF9CE86');
        $this->addSql('ALTER TABLE factura DROP FOREIGN KEY FK_F9EBA00968BCB606');
        $this->addSql('ALTER TABLE cuenta_criterio_analisis DROP FOREIGN KEY FK_AF040B095ABBE5F6');
        $this->addSql('ALTER TABLE subcuenta_criterio_analisis DROP FOREIGN KEY FK_52A4A7685ABBE5F6');
        $this->addSql('ALTER TABLE activo_fijo_cuentas DROP FOREIGN KEY FK_E0DF290186762CC7');
        $this->addSql('ALTER TABLE activo_fijo_cuentas DROP FOREIGN KEY FK_E0DF290174A5FFBA');
        $this->addSql('ALTER TABLE activo_fijo_cuentas DROP FOREIGN KEY FK_E0DF290180C608FA');
        $this->addSql('ALTER TABLE cuadre_diario DROP FOREIGN KEY FK_60ABEFD91ADA4D3F');
        $this->addSql('ALTER TABLE cuenta_criterio_analisis DROP FOREIGN KEY FK_AF040B091ADA4D3F');
        $this->addSql('ALTER TABLE movimiento_activo_fijo DROP FOREIGN KEY FK_A985A0DA1ADA4D3F');
        $this->addSql('ALTER TABLE saldo_cuentas DROP FOREIGN KEY FK_BB2B71AE1ADA4D3F');
        $this->addSql('ALTER TABLE subcuenta DROP FOREIGN KEY FK_57BB37EA1ADA4D3F');
        $this->addSql('ALTER TABLE ajuste DROP FOREIGN KEY FK_DD35BD326601BA07');
        $this->addSql('ALTER TABLE devolucion DROP FOREIGN KEY FK_524D9F676601BA07');
        $this->addSql('ALTER TABLE factura_documento DROP FOREIGN KEY FK_CCC060C16601BA07');
        $this->addSql('ALTER TABLE informe_recepcion DROP FOREIGN KEY FK_62A4EBD6601BA07');
        $this->addSql('ALTER TABLE movimiento_mercancia DROP FOREIGN KEY FK_44876BD76601BA07');
        $this->addSql('ALTER TABLE movimiento_producto DROP FOREIGN KEY FK_FFC0EDFC6601BA07');
        $this->addSql('ALTER TABLE obligacion_pago DROP FOREIGN KEY FK_403C9B3B6601BA07');
        $this->addSql('ALTER TABLE transferencia DROP FOREIGN KEY FK_EDC227306601BA07');
        $this->addSql('ALTER TABLE vale_salida DROP FOREIGN KEY FK_90C265C86601BA07');
        $this->addSql('ALTER TABLE activo_fijo_cuentas DROP FOREIGN KEY FK_E0DF2901A752F04B');
        $this->addSql('ALTER TABLE devolucion DROP FOREIGN KEY FK_524D9F67F66372E9');
        $this->addSql('ALTER TABLE factura DROP FOREIGN KEY FK_F9EBA009F66372E9');
        $this->addSql('ALTER TABLE movimiento_mercancia DROP FOREIGN KEY FK_44876BD7F66372E9');
        $this->addSql('ALTER TABLE movimiento_producto DROP FOREIGN KEY FK_FFC0EDFCF66372E9');
        $this->addSql('ALTER TABLE movimiento_venta DROP FOREIGN KEY FK_8E3F7AE5F0821C98');
        $this->addSql('ALTER TABLE saldo_cuentas DROP FOREIGN KEY FK_BB2B71AEF66372E9');
        $this->addSql('ALTER TABLE factura DROP FOREIGN KEY FK_F9EBA009F5DBAF2B');
        $this->addSql('ALTER TABLE movimiento_mercancia DROP FOREIGN KEY FK_44876BD7F5DBAF2B');
        $this->addSql('ALTER TABLE movimiento_producto DROP FOREIGN KEY FK_FFC0EDFCF5DBAF2B');
        $this->addSql('ALTER TABLE movimiento_venta DROP FOREIGN KEY FK_8E3F7AE56EA527F2');
        $this->addSql('ALTER TABLE saldo_cuentas DROP FOREIGN KEY FK_BB2B71AEF5DBAF2B');
        $this->addSql('ALTER TABLE factura_documento DROP FOREIGN KEY FK_CCC060C155C5F988');
        $this->addSql('ALTER TABLE facturas_comprobante DROP FOREIGN KEY FK_6FD2F19B55C5F988');
        $this->addSql('ALTER TABLE movimiento_mercancia DROP FOREIGN KEY FK_44876BD755C5F988');
        $this->addSql('ALTER TABLE movimiento_producto DROP FOREIGN KEY FK_FFC0EDFC55C5F988');
        $this->addSql('ALTER TABLE movimiento_venta DROP FOREIGN KEY FK_8E3F7AE555C5F988');
        $this->addSql('ALTER TABLE obligacion_cobro DROP FOREIGN KEY FK_807C726D55C5F988');
        $this->addSql('ALTER TABLE activo_fijo DROP FOREIGN KEY FK_75EBC93E4A667A2B');
        $this->addSql('ALTER TABLE mercancia_producto DROP FOREIGN KEY FK_3F705CF59F287F54');
        $this->addSql('ALTER TABLE movimiento_mercancia DROP FOREIGN KEY FK_44876BD79F287F54');
        $this->addSql('ALTER TABLE configuracion_inicial DROP FOREIGN KEY FK_8521BE24404AE9D2');
        $this->addSql('ALTER TABLE contratos_cliente DROP FOREIGN KEY FK_29A5BB47374388F5');
        $this->addSql('ALTER TABLE cuentas_cliente DROP FOREIGN KEY FK_64653310374388F5');
        $this->addSql('ALTER TABLE documento DROP FOREIGN KEY FK_B6B12EC7374388F5');
        $this->addSql('ALTER TABLE tasa_cambio DROP FOREIGN KEY FK_DAB48606FA5CADE9');
        $this->addSql('ALTER TABLE tasa_cambio DROP FOREIGN KEY FK_DAB48606D85CECF7');
        $this->addSql('ALTER TABLE activo_fijo_movimiento_activo_fijo DROP FOREIGN KEY FK_2FA61FF27786CA71');
        $this->addSql('ALTER TABLE factura_documento DROP FOREIGN KEY FK_CCC060C1EC34F77F');
        $this->addSql('ALTER TABLE devolucion DROP FOREIGN KEY FK_524D9F675074DD86');
        $this->addSql('ALTER TABLE factura DROP FOREIGN KEY FK_F9EBA00971381BB3');
        $this->addSql('ALTER TABLE movimiento_mercancia DROP FOREIGN KEY FK_44876BD771381BB3');
        $this->addSql('ALTER TABLE movimiento_producto DROP FOREIGN KEY FK_FFC0EDFC71381BB3');
        $this->addSql('ALTER TABLE movimiento_venta DROP FOREIGN KEY FK_8E3F7AE5FA3DF5CD');
        $this->addSql('ALTER TABLE saldo_cuentas DROP FOREIGN KEY FK_BB2B71AE71381BB3');
        $this->addSql('ALTER TABLE mercancia_producto DROP FOREIGN KEY FK_3F705CF56E57A479');
        $this->addSql('ALTER TABLE movimiento_producto DROP FOREIGN KEY FK_FFC0EDFC6E57A479');
        $this->addSql('ALTER TABLE informe_recepcion DROP FOREIGN KEY FK_62A4EBDE8F12801');
        $this->addSql('ALTER TABLE obligacion_pago DROP FOREIGN KEY FK_403C9B3BE8F12801');
        $this->addSql('ALTER TABLE saldo_cuentas DROP FOREIGN KEY FK_BB2B71AEE8F12801');
        $this->addSql('ALTER TABLE subcuenta_proveedor DROP FOREIGN KEY FK_5C22E4B8E8F12801');
        $this->addSql('ALTER TABLE comprobante_cierre DROP FOREIGN KEY FK_D03EA4C51800963C');
        $this->addSql('ALTER TABLE facturas_comprobante DROP FOREIGN KEY FK_6FD2F19B1800963C');
        $this->addSql('ALTER TABLE activo_fijo_cuentas DROP FOREIGN KEY FK_E0DF29014476721E');
        $this->addSql('ALTER TABLE activo_fijo_cuentas DROP FOREIGN KEY FK_E0DF2901549C81D9');
        $this->addSql('ALTER TABLE activo_fijo_cuentas DROP FOREIGN KEY FK_E0DF290157677646');
        $this->addSql('ALTER TABLE cuadre_diario DROP FOREIGN KEY FK_60ABEFD92D412F53');
        $this->addSql('ALTER TABLE movimiento_activo_fijo DROP FOREIGN KEY FK_A985A0DA2D412F53');
        $this->addSql('ALTER TABLE saldo_cuentas DROP FOREIGN KEY FK_BB2B71AE2D412F53');
        $this->addSql('ALTER TABLE subcuenta_criterio_analisis DROP FOREIGN KEY FK_52A4A7682D412F53');
        $this->addSql('ALTER TABLE subcuenta_proveedor DROP FOREIGN KEY FK_5C22E4B82D412F53');
        $this->addSql('ALTER TABLE registro_comprobantes DROP FOREIGN KEY FK_B2D1B2B2EF5F7851');
        $this->addSql('ALTER TABLE cuenta DROP FOREIGN KEY FK_31C7BFCF45E7F350');
        $this->addSql('ALTER TABLE configuracion_inicial DROP FOREIGN KEY FK_8521BE247A4F962');
        $this->addSql('ALTER TABLE documento DROP FOREIGN KEY FK_B6B12EC77A4F962');
        $this->addSql('ALTER TABLE movimiento_mercancia DROP FOREIGN KEY FK_44876BD77A4F962');
        $this->addSql('ALTER TABLE movimiento_producto DROP FOREIGN KEY FK_FFC0EDFC7A4F962');
        $this->addSql('ALTER TABLE movimiento DROP FOREIGN KEY FK_C8FF107AD1CE493D');
        $this->addSql('ALTER TABLE activo_fijo DROP FOREIGN KEY FK_75EBC93EDB763453');
        $this->addSql('ALTER TABLE activo_fijo DROP FOREIGN KEY FK_75EBC93E6FBA0327');
        $this->addSql('ALTER TABLE movimiento DROP FOREIGN KEY FK_C8FF107ADB763453');
        $this->addSql('ALTER TABLE movimiento_activo_fijo DROP FOREIGN KEY FK_A985A0DADB763453');
        $this->addSql('ALTER TABLE activo_fijo DROP FOREIGN KEY FK_75EBC93E1D34FA6B');
        $this->addSql('ALTER TABLE almacen DROP FOREIGN KEY FK_D5B2D2501D34FA6B');
        $this->addSql('ALTER TABLE area_responsabilidad DROP FOREIGN KEY FK_F469C2BA1D34FA6B');
        $this->addSql('ALTER TABLE centro_costo DROP FOREIGN KEY FK_749608CE1D34FA6B');
        $this->addSql('ALTER TABLE devolucion DROP FOREIGN KEY FK_524D9F671D34FA6B');
        $this->addSql('ALTER TABLE documento DROP FOREIGN KEY FK_B6B12EC71D34FA6B');
        $this->addSql('ALTER TABLE empleado DROP FOREIGN KEY FK_D9D9BF521D34FA6B');
        $this->addSql('ALTER TABLE expediente DROP FOREIGN KEY FK_D59CA4131D34FA6B');
        $this->addSql('ALTER TABLE factura DROP FOREIGN KEY FK_F9EBA0091D34FA6B');
        $this->addSql('ALTER TABLE facturas_comprobante DROP FOREIGN KEY FK_6FD2F19B1D34FA6B');
        $this->addSql('ALTER TABLE movimiento DROP FOREIGN KEY FK_C8FF107A873C7FC7');
        $this->addSql('ALTER TABLE movimiento DROP FOREIGN KEY FK_C8FF107A4F781EA');
        $this->addSql('ALTER TABLE movimiento_activo_fijo DROP FOREIGN KEY FK_A985A0DA1D34FA6B');
        $this->addSql('ALTER TABLE obligacion_pago DROP FOREIGN KEY FK_403C9B3B1D34FA6B');
        $this->addSql('ALTER TABLE orden_trabajo DROP FOREIGN KEY FK_4158A0241D34FA6B');
        $this->addSql('ALTER TABLE registro_comprobantes DROP FOREIGN KEY FK_B2D1B2B21D34FA6B');
        $this->addSql('ALTER TABLE saldo_cuentas DROP FOREIGN KEY FK_BB2B71AE1D34FA6B');
        $this->addSql('ALTER TABLE transferencia DROP FOREIGN KEY FK_EDC227301D34FA6B');
        $this->addSql('ALTER TABLE unidad DROP FOREIGN KEY FK_F3E6D02F31E700CD');
        $this->addSql('ALTER TABLE mercancia DROP FOREIGN KEY FK_9D094AE0E16A5625');
        $this->addSql('ALTER TABLE producto DROP FOREIGN KEY FK_A7BB0615E16A5625');
        $this->addSql('ALTER TABLE almacen_ocupado DROP FOREIGN KEY FK_AA5360587EB2C349');
        $this->addSql('ALTER TABLE cierre DROP FOREIGN KEY FK_D0DCFCC77EB2C349');
        $this->addSql('ALTER TABLE cierre_diario DROP FOREIGN KEY FK_F3D0CD897EB2C349');
        $this->addSql('ALTER TABLE custom_user DROP FOREIGN KEY FK_8CE51EB479F37AE5');
        $this->addSql('ALTER TABLE empleado DROP FOREIGN KEY FK_D9D9BF527EB2C349');
        $this->addSql('ALTER TABLE factura DROP FOREIGN KEY FK_F9EBA0097EB2C349');
        $this->addSql('ALTER TABLE movimiento_activo_fijo DROP FOREIGN KEY FK_A985A0DA7EB2C349');
        $this->addSql('ALTER TABLE movimiento_mercancia DROP FOREIGN KEY FK_44876BD77EB2C349');
        $this->addSql('ALTER TABLE movimiento_producto DROP FOREIGN KEY FK_FFC0EDFC7EB2C349');
        $this->addSql('ALTER TABLE registro_comprobantes DROP FOREIGN KEY FK_B2D1B2B27EB2C349');
        $this->addSql('DROP TABLE activo_fijo');
        $this->addSql('DROP TABLE activo_fijo_cuentas');
        $this->addSql('DROP TABLE activo_fijo_movimiento_activo_fijo');
        $this->addSql('DROP TABLE ajuste');
        $this->addSql('DROP TABLE almacen');
        $this->addSql('DROP TABLE almacen_ocupado');
        $this->addSql('DROP TABLE area_responsabilidad');
        $this->addSql('DROP TABLE cargo');
        $this->addSql('DROP TABLE carrito');
        $this->addSql('DROP TABLE centro_costo');
        $this->addSql('DROP TABLE cierre');
        $this->addSql('DROP TABLE cierre_diario');
        $this->addSql('DROP TABLE cliente');
        $this->addSql('DROP TABLE cliente_beneficiario');
        $this->addSql('DROP TABLE cliente_contabilidad');
        $this->addSql('DROP TABLE cliente_reporte');
        $this->addSql('DROP TABLE comprobante_cierre');
        $this->addSql('DROP TABLE configuracion_inicial');
        $this->addSql('DROP TABLE contratos_cliente');
        $this->addSql('DROP TABLE criterio_analisis');
        $this->addSql('DROP TABLE cuadre_diario');
        $this->addSql('DROP TABLE cuenta');
        $this->addSql('DROP TABLE cuenta_criterio_analisis');
        $this->addSql('DROP TABLE cuentas_cliente');
        $this->addSql('DROP TABLE custom_user');
        $this->addSql('DROP TABLE depreciacion');
        $this->addSql('DROP TABLE devolucion');
        $this->addSql('DROP TABLE documento');
        $this->addSql('DROP TABLE elemento_gasto');
        $this->addSql('DROP TABLE empleado');
        $this->addSql('DROP TABLE expediente');
        $this->addSql('DROP TABLE factura');
        $this->addSql('DROP TABLE factura_documento');
        $this->addSql('DROP TABLE facturas_comprobante');
        $this->addSql('DROP TABLE grupo_activos');
        $this->addSql('DROP TABLE informe_recepcion');
        $this->addSql('DROP TABLE instrumento_cobro');
        $this->addSql('DROP TABLE mercancia');
        $this->addSql('DROP TABLE mercancia_producto');
        $this->addSql('DROP TABLE modulo');
        $this->addSql('DROP TABLE moneda');
        $this->addSql('DROP TABLE movimiento');
        $this->addSql('DROP TABLE movimiento_activo_fijo');
        $this->addSql('DROP TABLE movimiento_mercancia');
        $this->addSql('DROP TABLE movimiento_producto');
        $this->addSql('DROP TABLE movimiento_venta');
        $this->addSql('DROP TABLE municipios');
        $this->addSql('DROP TABLE obligacion_cobro');
        $this->addSql('DROP TABLE obligacion_pago');
        $this->addSql('DROP TABLE orden_trabajo');
        $this->addSql('DROP TABLE producto');
        $this->addSql('DROP TABLE proveedor');
        $this->addSql('DROP TABLE provincias');
        $this->addSql('DROP TABLE registro_comprobantes');
        $this->addSql('DROP TABLE reset_password_request');
        $this->addSql('DROP TABLE saldo_cuentas');
        $this->addSql('DROP TABLE solicitud_turismo');
        $this->addSql('DROP TABLE stripe_factura');
        $this->addSql('DROP TABLE subcuenta');
        $this->addSql('DROP TABLE subcuenta_criterio_analisis');
        $this->addSql('DROP TABLE subcuenta_proveedor');
        $this->addSql('DROP TABLE tasa_cambio');
        $this->addSql('DROP TABLE test_crud');
        $this->addSql('DROP TABLE tipo_comprobante');
        $this->addSql('DROP TABLE tipo_cuenta');
        $this->addSql('DROP TABLE tipo_documento');
        $this->addSql('DROP TABLE tipo_documento_activo_fijo');
        $this->addSql('DROP TABLE tipo_movimiento');
        $this->addSql('DROP TABLE transferencia');
        $this->addSql('DROP TABLE unidad');
        $this->addSql('DROP TABLE unidad_medida');
        $this->addSql('DROP TABLE user');
        $this->addSql('DROP TABLE vale_salida');
    }
}
