<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZ3ldLUX\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZ3ldLUX/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerZ3ldLUX.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerZ3ldLUX\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerZ3ldLUX\App_KernelProdContainer([
    'container.build_hash' => 'Z3ldLUX',
    'container.build_id' => '37e453c1',
    'container.build_time' => 1596733929,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZ3ldLUX');
