<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'cliente-monto' => [['tel'], ['_controller' => 'App\\Controller\\ApiController::clienteMonto'], [], [['variable', '', '[^/]++', 'tel', true], ['text', '/cliente-monto']], [], []],
    'api.get-user' => [['tel', 'monto'], ['_controller' => 'App\\Controller\\ApiController::apiGetUser'], [], [['variable', '/', '[^/]++', 'monto', true], ['variable', '/', '[^/]++', 'tel', true], ['text', '/api.get-user']], [], []],
    'api.create' => [[], ['_controller' => 'App\\Controller\\ApiController::apiCreate'], [], [['text', '/api.create']], [], []],
    'api.status' => [[], ['_controller' => 'App\\Controller\\ApiController::apiStatus'], [], [['text', '/api.status']], [], []],
    'select' => [['tel'], ['_controller' => 'App\\Controller\\ApiController::select'], [], [['variable', '', '[^/]++', 'tel', true], ['text', '/select']], [], []],
    'api.security' => [[], ['_controller' => 'App\\Controller\\ApiController::apiSecurity'], [], [['text', '/api.security']], [], []],
    'api.form' => [['tel', 'monto', 'last4'], ['_controller' => 'App\\Controller\\ApiController::apiForm'], [], [['variable', '/', '[^/]++', 'last4', true], ['variable', '/', '[^/]++', 'monto', true], ['variable', '', '[^/]++', 'tel', true], ['text', '/api.form']], [], []],
    'confirm' => [['tel', 'monto', 'last4'], ['_controller' => 'App\\Controller\\ApiController::confirm'], [], [['variable', '/', '[^/]++', 'last4', true], ['variable', '/', '[^/]++', 'monto', true], ['variable', '/', '[^/]++', 'tel', true], ['text', '/confirm']], [], []],
    'cliente-index' => [[], ['_controller' => 'App\\Controller\\ClienteController::clienteIndex'], [], [['text', '/cliente-index']], [], []],
    'registrar-cliente' => [['tel'], ['_controller' => 'App\\Controller\\ClienteController::registrarCliente'], [], [['variable', '', '[^/]++', 'tel', true], ['text', '/registrar-cliente']], [], []],
    'cliente-edit' => [['tel'], ['_controller' => 'App\\Controller\\ClienteController::clienteEdit'], [], [['variable', '', '[^/]++', 'tel', true], ['text', '/cliente-edit']], [], []],
    'edit-save' => [['tel'], ['_controller' => 'App\\Controller\\ClienteController::editSave'], [], [['variable', '', '[^/]++', 'tel', true], ['text', '/edit-save']], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\HomeController::home'], [], [['text', '/home']], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/']], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], []],
];
