<?php

namespace ContainerZ3ldLUX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getClienteControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\ClienteController' shared autowired service.
     *
     * @return \App\Controller\ClienteController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\ClienteController'] = $instance = new \App\Controller\ClienteController();

        $instance->setContainer(($container->privates['.service_locator.g9CqTPp'] ?? $container->load('get_ServiceLocator_G9CqTPpService'))->withContext('App\\Controller\\ClienteController', $container));

        return $instance;
    }
}
