<?php

namespace ContainerZ3ldLUX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getClienteRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\ClienteRepository' shared autowired service.
     *
     * @return \App\Repository\ClienteRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\ClienteRepository'] = new \App\Repository\ClienteRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
