<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container55gpecK\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container55gpecK/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container55gpecK.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container55gpecK\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container55gpecK\App_KernelDevDebugContainer([
    'container.build_hash' => '55gpecK',
    'container.build_id' => 'd8168b5c',
    'container.build_time' => 1595347401,
], __DIR__.\DIRECTORY_SEPARATOR.'Container55gpecK');
