<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerN6BcrvG\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerN6BcrvG/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerN6BcrvG.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerN6BcrvG\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerN6BcrvG\App_KernelDevDebugContainer([
    'container.build_hash' => 'N6BcrvG',
    'container.build_id' => 'cef91dcb',
    'container.build_time' => 1595693953,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerN6BcrvG');
