<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZ2xWHTl\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZ2xWHTl/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZ2xWHTl.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZ2xWHTl\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZ2xWHTl\App_KernelDevDebugContainer([
    'container.build_hash' => 'Z2xWHTl',
    'container.build_id' => 'ff0955dd',
    'container.build_time' => 1595603860,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZ2xWHTl');
