<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    'cliente-monto' => [['tel'], ['_controller' => 'App\\Controller\\ApiController::clienteMonto'], [], [['variable', '', '[^/]++', 'tel', true], ['text', '/cliente-monto']], [], []],
    'api.get-user' => [['tel', 'monto'], ['_controller' => 'App\\Controller\\ApiController::apiGetUser'], [], [['variable', '/', '[^/]++', 'monto', true], ['variable', '/', '[^/]++', 'tel', true], ['text', '/api.get-user']], [], []],
    'api.create' => [[], ['_controller' => 'App\\Controller\\ApiController::apiCreate'], [], [['text', '/api.create']], [], []],
    'api.status' => [[], ['_controller' => 'App\\Controller\\ApiController::apiStatus'], [], [['text', '/api.status']], [], []],
    'select' => [['tel'], ['_controller' => 'App\\Controller\\ApiController::select'], [], [['variable', '', '[^/]++', 'tel', true], ['text', '/select']], [], []],
    'api.security' => [[], ['_controller' => 'App\\Controller\\ApiController::apiSecurity'], [], [['text', '/api.security']], [], []],
    'api.form' => [['tel', 'monto', 'last4'], ['_controller' => 'App\\Controller\\ApiController::apiForm'], [], [['variable', '/', '[^/]++', 'last4', true], ['variable', '/', '[^/]++', 'monto', true], ['variable', '', '[^/]++', 'tel', true], ['text', '/api.form']], [], []],
    'confirm' => [['tel', 'monto', 'last4'], ['_controller' => 'App\\Controller\\ApiController::confirm'], [], [['variable', '/', '[^/]++', 'last4', true], ['variable', '/', '[^/]++', 'monto', true], ['variable', '/', '[^/]++', 'tel', true], ['text', '/confirm']], [], []],
    'cliente-index' => [[], ['_controller' => 'App\\Controller\\ClienteController::clienteIndex'], [], [['text', '/cliente-index']], [], []],
    'registrar-cliente' => [['tel'], ['_controller' => 'App\\Controller\\ClienteController::registrarCliente'], [], [['variable', '', '[^/]++', 'tel', true], ['text', '/registrar-cliente']], [], []],
    'cliente-edit' => [['tel'], ['_controller' => 'App\\Controller\\ClienteController::clienteEdit'], [], [['variable', '', '[^/]++', 'tel', true], ['text', '/cliente-edit']], [], []],
    'edit-save' => [['tel'], ['_controller' => 'App\\Controller\\ClienteController::editSave'], [], [['variable', '', '[^/]++', 'tel', true], ['text', '/edit-save']], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\HomeController::home'], [], [['text', '/home']], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/']], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], []],
];
